/* Fritz Academy Persistent Illustrated Builder v58
   Open campus placement + click-to-place + drag + zoom + pan + focus areas. */
class BuilderEngine{
  constructor(scene,lessonEngine){this.scene=scene;this.lessonEngine=lessonEngine;this.lesson=null;this.build=null;this.onComplete=null;this.overlay=null;this.viewport=null;this.stage=null;this.selectedId='';this.placementId='';this.drag=null;this.zoom=1;this.panX=0;this.panY=0;this.boundMove=e=>this.onPointerMove(e);this.boundUp=e=>this.onPointerUp(e);}
  start(lesson,onComplete){this.lesson=lesson;this.build=lesson&&lesson.build;this.onComplete=onComplete;if(!this.build||!Array.isArray(this.build.requiredPieces)||!this.build.requiredPieces.length){this.scene.panels.message('Build Area Missing','This game session does not contain a complete Academy build.');return;}this.lessonEngine.setSection('build');this.ensureSaveData();this.openBuilder();}
  ensureSaveData(){const s=this.scene.save;s.builderWorlds=s.builderWorlds||{};s.builderWorlds[this.build.areaId]=s.builderWorlds[this.build.areaId]||{};s.academyBuilds=s.academyBuilds||{};saveGame(s);}
  world(){return this.scene.save.builderWorlds[this.build.areaId];}
  allPieceSources(level){return[level&&level.feelingsActivity,level&&level.story,level&&level.phonics,level&&level.reader1,level&&level.reader2].filter(Boolean).map(x=>x.rewardPiece).filter(Boolean);}
  pieceCatalog(){const out={};(Array.isArray(window.LEVELS)?window.LEVELS:[]).forEach(level=>this.allPieceSources(level).forEach(piece=>{if(piece&&piece.id)out[piece.id]=piece;}));this.allPieceSources(this.lesson).forEach(piece=>{if(piece&&piece.id)out[piece.id]=piece;});return out;}
  earnedIds(){const ids=new Set();Object.values(this.scene.save.lessonProgress||{}).forEach(p=>(p&&Array.isArray(p.earnedPieces)?p.earnedPieces:[]).forEach(id=>ids.add(id)));const current=this.lessonEngine.progress();(current&&Array.isArray(current.earnedPieces)?current.earnedPieces:[]).forEach(id=>ids.add(id));return[...ids];}
  piece(id){return this.pieceCatalog()[id]||{id,name:id,icon:''};}
  art(piece){return window.FRITZ_BUILDER_ART&&typeof window.FRITZ_BUILDER_ART.resolve==='function'?window.FRITZ_BUILDER_ART.resolve(piece):'assets/alphabet-blocks.png';}
  isPlaced(id){return Boolean(this.world()[id]);}isComplete(){return this.build.requiredPieces.every(id=>this.isPlaced(id));}
  injectStyles(){if(document.getElementById('fritz-builder58-style'))return;const style=document.createElement('style');style.id='fritz-builder58-style';style.textContent=`
.fa-builder58{position:fixed;inset:0;z-index:10050;background:#061426;display:flex;flex-direction:column;color:#102342;font-family:Arial,sans-serif}.fa-builder58 *{box-sizing:border-box}
.fa-builder58-head{min-height:82px;display:flex;align-items:center;gap:10px;padding:8px 14px;background:#fff5d7;border-bottom:4px solid #d6ad43}.fa-builder58-title{font-size:23px;font-weight:900;flex:1}.fa-builder58-sub{font-size:13px;color:#46566f;margin-top:3px}.fa-builder58-btn{border:2px solid #173f72;border-radius:11px;background:#fff;padding:9px 13px;font-weight:900;color:#102342;cursor:pointer}.fa-builder58-btn.primary{background:#f3c84b}.fa-builder58-btn:disabled{opacity:.45;cursor:not-allowed}
.fa-builder58-main{position:relative;flex:1;min-height:0;overflow:hidden;background:#6f9a69}.fa-builder58-view{position:absolute;inset:0;overflow:hidden;touch-action:none;cursor:grab}.fa-builder58-view.panning{cursor:grabbing}.fa-builder58-stage{position:absolute;inset:0;background:url('assets/fritz_academy_world_map.png') center center/cover no-repeat;transform-origin:center center;will-change:transform;touch-action:none}
.fa-builder58-piece{position:absolute;width:108px;height:108px;object-fit:contain;transform:translate(-50%,-50%);filter:drop-shadow(0 6px 5px rgba(0,0,0,.35));cursor:grab;user-select:none;-webkit-user-drag:none;touch-action:none}.fa-builder58-piece.sel{outline:4px solid #ffd84a;outline-offset:4px;border-radius:10px}.fa-builder58-piece.drag{cursor:grabbing;z-index:999!important}
.fa-builder58-placehint{position:absolute;top:14px;left:50%;transform:translateX(-50%);z-index:12;background:rgba(255,248,220,.94);border:3px solid #e0b841;border-radius:14px;padding:9px 16px;font-weight:900;pointer-events:none;display:none}.fa-builder58-placehint.on{display:block}
.fa-builder58-focus{position:absolute;top:14px;left:14px;z-index:11;display:flex;gap:6px;flex-wrap:wrap;max-width:62%}.fa-builder58-focus button{border:2px solid #173f72;background:rgba(255,255,255,.92);border-radius:999px;padding:7px 10px;font-weight:800;cursor:pointer;color:#102342}
.fa-builder58-foot{height:164px;background:#fff5d7;border-top:4px solid #d6ad43;display:flex;gap:12px;padding:9px 13px;align-items:stretch}.fa-builder58-pack{flex:1;display:flex;gap:9px;overflow-x:auto;padding:3px 2px 8px;align-items:center}.fa-builder58-card{width:106px;min-width:106px;height:132px;background:#fff;border:2px solid #d6c18a;border-radius:13px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:4px;padding:5px;cursor:pointer;box-shadow:0 3px 7px rgba(0,0,0,.12)}.fa-builder58-card img{width:76px;height:76px;object-fit:contain}.fa-builder58-card strong{font-size:12px;text-align:center;line-height:1.05}.fa-builder58-card.current{border-color:#174ea6}.fa-builder58-card.placed{opacity:.5}.fa-builder58-card.placing{outline:4px solid #f3c84b}
.fa-builder58-side{width:225px;border-left:1px solid #cdbb91;padding-left:12px;display:flex;flex-direction:column;justify-content:center;gap:7px}.fa-builder58-status{font-size:13px;font-weight:900;line-height:1.35}.fa-builder58-hint{font-size:12px;color:#46566f;line-height:1.25}
@media(max-width:760px){.fa-builder58-head{min-height:72px}.fa-builder58-title{font-size:18px}.fa-builder58-sub{display:none}.fa-builder58-foot{height:150px}.fa-builder58-side{width:155px}.fa-builder58-card{min-width:95px;width:95px}.fa-builder58-piece{width:90px;height:90px}.fa-builder58-focus{max-width:80%}}
`;document.head.appendChild(style);}
  openBuilder(){this.closeBuilder(false);this.injectStyles();if(this.scene.panels&&this.scene.panels.close)this.scene.panels.close();if(this.scene.physics&&this.scene.physics.world)this.scene.physics.pause();const root=document.createElement('div');root.className='fa-builder58';
    const head=document.createElement('div');head.className='fa-builder58-head';const tw=document.createElement('div');tw.style.flex='1';const title=document.createElement('div');title.className='fa-builder58-title';title.textContent=this.build.title||'Build Your Fritz Academy';const sub=document.createElement('div');sub.className='fa-builder58-sub';sub.textContent='Choose a piece, place it anywhere, then zoom and pan to build your own Academy.';tw.append(title,sub);
    const zoomOut=this.button('−',()=>this.setZoom(this.zoom-.25));const zoomIn=this.button('+',()=>this.setZoom(this.zoom+.25));const full=this.button('Full Campus',()=>this.focusArea('full'));const reset=this.button('Return Selected',()=>this.returnSelected());const finish=this.button('Place All New Pieces',()=>this.finishBuild(),'primary');finish.id='fa-builder58-finish';head.append(tw,zoomOut,zoomIn,full,reset,finish);
    const main=document.createElement('div');main.className='fa-builder58-main';const view=document.createElement('div');view.className='fa-builder58-view';const stage=document.createElement('div');stage.className='fa-builder58-stage';view.appendChild(stage);main.appendChild(view);this.viewport=view;this.stage=stage;
    const hint=document.createElement('div');hint.className='fa-builder58-placehint';hint.id='fa-builder58-placehint';main.appendChild(hint);
    const focus=document.createElement('div');focus.className='fa-builder58-focus';[['Front Gate','gate'],['Welcome Garden','garden'],['Pond','pond'],['Workshop','workshop']].forEach(([label,key])=>{const b=document.createElement('button');b.textContent=label;b.onclick=e=>{e.stopPropagation();this.focusArea(key);};focus.appendChild(b);});main.appendChild(focus);
    view.addEventListener('pointerdown',e=>this.beginCanvasPointer(e));view.addEventListener('click',e=>this.canvasClick(e));
    const foot=document.createElement('div');foot.className='fa-builder58-foot';const pack=document.createElement('div');pack.className='fa-builder58-pack';pack.id='fa-builder58-pack';const side=document.createElement('div');side.className='fa-builder58-side';const status=document.createElement('div');status.className='fa-builder58-status';status.id='fa-builder58-status';const help=document.createElement('div');help.className='fa-builder58-hint';help.textContent='Click a Builder Pack item, then click the exact spot on the Academy. Drag placed items. Drag empty ground to pan when zoomed.';side.append(status,help);foot.append(pack,side);root.append(head,main,foot);document.body.appendChild(root);this.overlay=root;window.addEventListener('pointermove',this.boundMove,{passive:false});window.addEventListener('pointerup',this.boundUp);this.applyView();this.render();}
  button(text,fn,kind=''){const b=document.createElement('button');b.className='fa-builder58-btn'+(kind?' '+kind:'');b.textContent=text;b.onclick=fn;return b;}
  applyView(){if(this.stage)this.stage.style.transform=`translate(${this.panX}px,${this.panY}px) scale(${this.zoom})`;}
  setZoom(z){this.zoom=Math.max(1,Math.min(3,z));if(this.zoom===1){this.panX=0;this.panY=0;}this.applyView();}
  focusArea(key){const presets={full:[1,0,0],gate:[2.0,0,115],garden:[2.0,250,80],pond:[2.25,-260,105],workshop:[2.25,-150,-90]};const p=presets[key]||presets.full;this.zoom=p[0];this.panX=p[1];this.panY=p[2];this.applyView();}
  render(){if(!this.overlay||!this.stage)return;this.stage.querySelectorAll('.fa-builder58-piece').forEach(n=>n.remove());const pack=this.overlay.querySelector('#fa-builder58-pack');pack.innerHTML='';const catalog=this.pieceCatalog();const earned=this.earnedIds().filter(id=>catalog[id]);const world=this.world();Object.keys(world).forEach((id,index)=>{const piece=this.piece(id),pos=world[id];const img=document.createElement('img');img.className='fa-builder58-piece'+(this.selectedId===id?' sel':'');img.src=this.art(piece);img.alt=piece.name;img.title=piece.name;img.dataset.id=id;img.style.left=`${Math.max(.02,Math.min(.98,Number(pos.x)||.5))*100}%`;img.style.top=`${Math.max(.03,Math.min(.97,Number(pos.y)||.5))*100}%`;img.style.zIndex=String(pos.z||20+index);img.addEventListener('pointerdown',e=>this.beginPieceDrag(e,id,img));img.addEventListener('click',e=>{e.stopPropagation();this.selectedId=id;this.placementId='';this.render();});this.stage.appendChild(img);});earned.forEach(id=>{const piece=this.piece(id),card=document.createElement('button');card.className='fa-builder58-card';if(this.build.requiredPieces.includes(id))card.classList.add('current');if(world[id])card.classList.add('placed');if(this.placementId===id)card.classList.add('placing');const img=document.createElement('img');img.src=this.art(piece);const label=document.createElement('strong');label.textContent=piece.name;card.append(img,label);card.onclick=()=>{if(world[id]){this.selectedId=id;this.placementId='';}else{this.placementId=id;this.selectedId='';}this.render();};pack.appendChild(card);});const ph=this.overlay.querySelector('#fa-builder58-placehint');if(this.placementId){ph.textContent=`Place ${this.piece(this.placementId).name}: click anywhere on the Academy`;ph.classList.add('on');}else ph.classList.remove('on');this.updateStatus();}
  canvasClick(e){if(!this.placementId||e.target!==this.viewport&&e.target!==this.stage)return;const r=this.stage.getBoundingClientRect();const x=Math.max(.015,Math.min(.985,(e.clientX-r.left)/r.width));const y=Math.max(.02,Math.min(.98,(e.clientY-r.top)/r.height));const id=this.placementId;this.world()[id]={x,y,z:50+Object.keys(this.world()).length};this.placementId='';this.selectedId=id;saveGame(this.scene.save);this.render();}
  beginPieceDrag(e,id,img){e.preventDefault();e.stopPropagation();this.placementId='';this.selectedId=id;img.classList.add('drag','sel');this.drag={mode:'piece',id,img};}
  beginCanvasPointer(e){if(this.placementId||e.target!==this.viewport&&e.target!==this.stage)return;if(this.zoom<=1)return;this.drag={mode:'pan',startX:e.clientX,startY:e.clientY,panX:this.panX,panY:this.panY};this.viewport.classList.add('panning');}
  onPointerMove(e){if(!this.drag)return;e.preventDefault();if(this.drag.mode==='pan'){this.panX=this.drag.panX+(e.clientX-this.drag.startX);this.panY=this.drag.panY+(e.clientY-this.drag.startY);this.applyView();return;}if(this.drag.mode==='piece'){const r=this.stage.getBoundingClientRect();const x=Math.max(.015,Math.min(.985,(e.clientX-r.left)/r.width));const y=Math.max(.02,Math.min(.98,(e.clientY-r.top)/r.height));this.drag.img.style.left=`${x*100}%`;this.drag.img.style.top=`${y*100}%`;const p=this.world()[this.drag.id]||{};p.x=x;p.y=y;p.z=999;this.world()[this.drag.id]=p;}}
  onPointerUp(){if(!this.drag)return;if(this.drag.mode==='piece'){const p=this.world()[this.drag.id];if(p)p.z=50+Object.keys(this.world()).indexOf(this.drag.id);saveGame(this.scene.save);this.render();}if(this.viewport)this.viewport.classList.remove('panning');this.drag=null;}
  returnSelected(){if(!this.selectedId||!this.world()[this.selectedId])return;delete this.world()[this.selectedId];this.selectedId='';saveGame(this.scene.save);this.render();}
  updateStatus(){if(!this.overlay)return;const placed=this.build.requiredPieces.filter(id=>this.isPlaced(id)).length,total=this.build.requiredPieces.length,complete=placed===total;const el=this.overlay.querySelector('#fa-builder58-status');el.textContent=complete?`All ${total} new pieces are placed. Your Academy is ready to save.`:`This session: ${placed} of ${total} new pieces placed.`;const btn=this.overlay.querySelector('#fa-builder58-finish');btn.disabled=!complete;btn.textContent=complete?'Save Build & Finish':'Place All New Pieces';}
  finishBuild(){if(!this.isComplete())return;this.scene.save.academyBuilds[this.build.areaId]=Math.max(this.scene.save.academyBuilds[this.build.areaId]||0,this.build.stage||1);saveGame(this.scene.save);const cb=this.onComplete;this.onComplete=null;this.closeBuilder(true);if(typeof cb==='function')cb();}
  closeBuilder(resume=true){window.removeEventListener('pointermove',this.boundMove);window.removeEventListener('pointerup',this.boundUp);if(this.overlay){this.overlay.remove();this.overlay=null;}this.viewport=null;this.stage=null;this.drag=null;this.placementId='';if(resume&&this.scene&&this.scene.physics&&this.scene.physics.world)this.scene.physics.resume();}
}
window.BuilderEngine=BuilderEngine;