/* Fritz Academy Builder Engine v53.0.0
   Game-like visual build board, persistent placements, strict completion, faster interaction. */
class BuilderEngine{
  constructor(scene,lessonEngine){this.scene=scene;this.lessonEngine=lessonEngine;this.lesson=null;this.build=null;this.selectedPieceId="";this.onComplete=null;}
  start(lesson,onComplete){this.lesson=lesson;this.build=lesson&&lesson.build;this.selectedPieceId="";this.onComplete=onComplete;if(!this.build||!Array.isArray(this.build.requiredPieces)||!this.build.requiredPieces.length){this.scene.panels.message("Build Area Missing","This adventure does not contain a complete Builder activity.");return;}this.lessonEngine.setSection("build");this.ensureSaveData();this.showBuilder();}
  ensureSaveData(){const s=this.scene.save;s.placedBuilds=s.placedBuilds||{};s.placedBuilds[this.build.areaId]=s.placedBuilds[this.build.areaId]||{};s.placedBuilds[this.build.areaId][this.build.stage]=s.placedBuilds[this.build.areaId][this.build.stage]||{};saveGame(s);}
  placements(){return this.scene.save.placedBuilds[this.build.areaId][this.build.stage];}
  earnedPieces(){const p=this.lessonEngine.progress();return p&&Array.isArray(p.earnedPieces)?p.earnedPieces:[];}
  sources(){return [this.lesson.feelingsActivity,this.lesson.story,this.lesson.phonics,this.lesson.reader1,this.lesson.reader2];}
  findPiece(id){for(const src of this.sources()){if(src&&src.rewardPiece&&src.rewardPiece.id===id)return src.rewardPiece;}return{id,name:id,icon:"⭐"};}
  pieceInSlot(i){const p=this.placements();return Object.keys(p).find(id=>p[id]===i)||"";}
  isPlaced(id){return Object.prototype.hasOwnProperty.call(this.placements(),id);}
  addLabel(objects,x,y,text,style={}){const t=this.scene.add.text(x,y,text,Object.assign({fontSize:"18px",fontStyle:"bold",color:"#102342",align:"center",wordWrap:{width:180}},style)).setOrigin(.5);objects.push(t);return t;}
  addCard(objects,x,y,w,h,fill,stroke=0xD2B66A,radius=18){const g=this.scene.add.graphics();g.fillStyle(fill,1);g.lineStyle(3,stroke,1);g.fillRoundedRect(x-w/2,y-h/2,w,h,radius);g.strokeRoundedRect(x-w/2,y-h/2,w,h,radius);objects.push(g);return g;}
  sceneTitle(){return (this.lesson&&this.lesson.reward)||'Academy Builder';}
  areaLabel(){return String(this.build.areaId||'academy-build').replace(/-/g,' ').replace(/\b\w/g,c=>c.toUpperCase());}
  showBuilder(){const earned=this.earnedPieces(),required=this.build.requiredPieces,placedCount=required.filter(id=>this.isPlaced(id)).length,allEarned=required.every(id=>earned.includes(id)),objects=[];
    const backdrop=this.scene.add.graphics();backdrop.fillStyle(0x102342,1);backdrop.fillRoundedRect(-455,-330,910,660,28);backdrop.fillStyle(0xF6EED7,1);backdrop.fillRoundedRect(-435,-310,870,620,24);objects.push(backdrop);
    this.addLabel(objects,0,-275,'FRITZ ACADEMY BUILDER',{fontSize:'18px',color:'#B78318',wordWrap:{width:700}});
    this.addLabel(objects,0,-238,this.build.title||'Build Your Academy',{fontSize:'31px',color:'#19365F',wordWrap:{width:720}});
    this.addLabel(objects,0,-205,`${this.areaLabel()}  •  Stage ${this.build.stage}`,{fontSize:'15px',color:'#6B5428',wordWrap:{width:700}});
    const barBack=this.scene.add.graphics();barBack.fillStyle(0xD9D0BA,1);barBack.fillRoundedRect(-280,-177,560,16,8);objects.push(barBack);const ratio=required.length?placedCount/required.length:0;if(ratio>0){const bar=this.scene.add.graphics();bar.fillStyle(0xD8A83B,1);bar.fillRoundedRect(-280,-177,560*ratio,16,8);objects.push(bar);}this.addLabel(objects,0,-150,`${placedCount}/${required.length} pieces placed`,{fontSize:'16px',color:'#46566F'});
    const helper=allEarned?(this.selectedPieceId?'Tap a glowing build spot to place it.':'Choose a piece from your Builder Pack.'):'Finish the episode activities to unlock every build piece.';this.addLabel(objects,0,-120,helper,{fontSize:'16px',color:allEarned?'#174EA6':'#A3472F',wordWrap:{width:700}});
    const slots=[[-250,-30],[0,-30],[250,-30],[-125,95],[125,95]];
    required.forEach((id,i)=>{const [x,y]=slots[i]||[-250+(i%3)*250,-30+Math.floor(i/3)*125],placedId=this.pieceInSlot(i),piece=placedId?this.findPiece(placedId):null,selectedReady=!!this.selectedPieceId;this.addCard(objects,x,y,200,102,piece?0xE8F3E6:(selectedReady?0xFFF0AE:0xFCF9F1),piece?0x5E9F64:(selectedReady?0xD39B1F:0xC8B98E),16);
      if(piece){const emblem=this.scene.add.circle(x,y-12,28,0xFFFFFF,1).setStrokeStyle(2,0xD9C999);objects.push(emblem);const icon=this.scene.add.text(x,y-12,piece.icon||'⭐',{fontSize:'34px'}).setOrigin(.5);objects.push(icon);this.addLabel(objects,x,y+29,piece.name,{fontSize:'14px',color:'#245C32',wordWrap:{width:168}});}else{const target=this.scene.add.circle(x,y-10,28,selectedReady?0xF7D364:0xEEE6D2,1).setStrokeStyle(3,selectedReady?0xC18A16:0xC8B98E,1).setInteractive({useHandCursor:true});target.on('pointerup',()=>this.placeSelected(i));objects.push(target);this.addLabel(objects,x,y-10,selectedReady?'＋':'•',{fontSize:'30px',color:selectedReady?'#7A5610':'#9A8B66'});this.addLabel(objects,x,y+31,selectedReady?'Place Here':`Build Spot ${i+1}`,{fontSize:'14px',color:selectedReady?'#7A5610':'#7A6A45'});}
    });
    this.addLabel(objects,0,164,'BUILDER PACK',{fontSize:'16px',color:'#6B5428'});
    const unplaced=required.filter(id=>earned.includes(id)&&!this.isPlaced(id)),packX=unplaced.length<=1?[0]:unplaced.length===2?[-155,155]:[-280,-140,0,140,280];
    if(!unplaced.length)this.addLabel(objects,0,218,allEarned?'All pieces are on the board.':'Earned pieces appear here.',{fontSize:'15px',color:'#7A6A45'});
    unplaced.forEach((id,i)=>{const p=this.findPiece(id),selected=this.selectedPieceId===id,x=packX[i]||0;this.addCard(objects,x,218,122,84,selected?0xF8D76A:0xFFFFFF,selected?0xB78318:0xD6C79B,14);const badge=this.scene.add.circle(x,204,22,selected?0xFFF7D3:0xF7F3E7,1).setStrokeStyle(2,selected?0xB78318:0xD6C79B).setInteractive({useHandCursor:true});badge.on('pointerup',()=>{this.selectedPieceId=id;this.showBuilder();});objects.push(badge);const c=this.scene.add.text(x,204,p.icon||'⭐',{fontSize:'27px'}).setOrigin(.5).setInteractive({useHandCursor:true});c.on('pointerup',()=>{this.selectedPieceId=id;this.showBuilder();});objects.push(c);const n=this.scene.add.text(x,241,p.name,{fontSize:'11px',fontStyle:'bold',color:'#19365F',align:'center',wordWrap:{width:104}}).setOrigin(.5).setInteractive({useHandCursor:true});n.on('pointerup',()=>{this.selectedPieceId=id;this.showBuilder();});objects.push(n);});
    const complete=this.isComplete(),action=this.scene.panels.makeButton(0,292,complete?'Complete the Build':'Place Every Piece',()=>{if(complete)this.completeBuild();},{fontSize:'19px',backgroundColor:complete?'#F6C744':'#DAD3C2',padding:{x:26,y:9}});objects.push(action);this.scene.panels.open(objects,{width:960,height:720});}
  placeSelected(slotIndex){if(!this.selectedPieceId)return;const earned=this.earnedPieces();if(!earned.includes(this.selectedPieceId))return;const placements=this.placements(),occupying=this.pieceInSlot(slotIndex);if(occupying)delete placements[occupying];placements[this.selectedPieceId]=slotIndex;this.selectedPieceId='';saveGame(this.scene.save);this.showBuilder();}
  isComplete(){const p=this.placements();return this.build.requiredPieces.every(id=>Object.prototype.hasOwnProperty.call(p,id));}
  completeBuild(){if(!this.isComplete())return;const s=this.scene.save;s.academyBuilds=s.academyBuilds||{};s.academyBuilds[this.build.areaId]=Math.max(s.academyBuilds[this.build.areaId]||0,this.build.stage);saveGame(s);const objects=[];const bg=this.scene.add.graphics();bg.fillStyle(0x102342,1);bg.fillRoundedRect(-370,-235,740,470,26);bg.fillStyle(0xFFF7DF,1);bg.fillRoundedRect(-350,-215,700,430,22);objects.push(bg);this.addLabel(objects,0,-145,'BUILD COMPLETE!',{fontSize:'36px',color:'#2F7D32'});this.addLabel(objects,0,-92,this.sceneTitle(),{fontSize:'19px',color:'#B78318',wordWrap:{width:600}});const sparkle=this.scene.add.text(0,-25,'★  ✦  ★',{fontSize:'48px',color:'#D8A83B'}).setOrigin(.5);objects.push(sparkle);this.addLabel(objects,0,55,this.build.completionMessage||'Your new Academy section has been saved.',{fontSize:'22px',color:'#19365F',wordWrap:{width:590}});const cont=this.scene.panels.makeButton(0,150,'Continue the Adventure',()=>this.finish(),{fontSize:'19px',backgroundColor:'#F6C744'});objects.push(cont);this.scene.panels.open(objects,{width:800,height:540});}
  finish(){const cb=this.onComplete;this.onComplete=null;if(typeof cb==='function')cb();}
}
window.BuilderEngine=BuilderEngine;