/* Canonical Fritz Academy foundation runtime lessons 7-9. */
(function(){
  if(typeof LEVELS==='undefined'||!Array.isArray(LEVELS)) return;
  const music={title:'Fritz Academy Alphabet Song',rewardMessage:'Sing the alphabet and point to every letter you know!',assetPath:'assets/audio/alphabet-song.mp3',videoPath:'assets/video/alphabet-song.mp4'};
  const closing={title:'Fritz Academy Welcome Theme',assetPath:'assets/audio/fritz-academy-theme.mp3',videoPath:'assets/video/fritz-academy-theme.mp4',rewardMessage:'Celebrate your Academy progress!'};
  const put=(id,lesson)=>{const i=LEVELS.findIndex(x=>x&&x.id===id); if(i>=0) LEVELS[i]=lesson; else LEVELS.push(lesson);};

  put('3-A',{
    id:'3-A',chapter:'Week 3',title:'When Is It? S T U',unlocked:false,reward:'Learning Room — Time Corner',buildArea:'learning-room',buildStage:4,canonicalLesson:7,
    objectives:{speaking:['Answer simple WHEN questions with now, later, morning, or night.','Use first/then in highly supported routines.','Say S, T, U and their useful sounds.'],listening:['Understand WHEN as asking about time or sequence.','Match familiar actions to morning/night.','Hear /s/, /t/, short /u/.'],reading:['Recognize S T U and s t u.','Read when, now and familiar routine words.','Read short controlled time sentences.'],writing:['Identify and trace/copy S s, T t, U u.'],phonics:['S—sun /s/.','T—top /t/.','U—up short /u/.']},
    vocabulary:[{word:'when',display:'When?',picture:'❓'},{word:'now',display:'Now.',picture:'⏱️'},{word:'later',display:'Later.',picture:'➡️'},{word:'morning',display:'in the morning',picture:'🌅'},{word:'night',display:'at night',picture:'🌙'},{word:'then',display:'Then ___.',picture:'➡️'}],
    intro:[{speaker:'Captain Fritz',text:'Today we learn WHEN. WHEN asks about time.'},{speaker:'Captain Fritz',text:'When do we start? We start now.'},{speaker:'Captain Fritz',text:'We will use morning, night, now, and later while we learn S, T, U.'}],
    feelingChoices:[{id:'ready',label:'I am ready.',emoji:'⭐'},{id:'happy',label:'I am happy.',emoji:'😀'},{id:'okay',label:'I am okay.',emoji:'🙂'}],
    feelingsActivity:{title:'When?',instructions:'Choose the answer that tells time or sequence.',questions:[{emoji:'🌅',prompt:'When does the Academy day begin?',options:['In the morning.','At night.','Under the table.'],answer:'In the morning.'},{emoji:'🌙',prompt:'When do we sleep?',options:['At night.','In the box.','Who is this?'],answer:'At night.'},{emoji:'⏱️',prompt:'When do we start this game?',options:['Now.','A dog.','Three.'],answer:'Now.'}],rewardPiece:{id:'when-clock',name:'WHEN Clock',icon:'🕒',area:'learning-room',lesson:'3-A'}},
    story:{title:'The Academy Clock',pages:[{text:'Fritz finds a clock for the Learning Room.',image:'assets/captain_fritz.png'},{text:'Bash asks, “When do we put it up?”',image:'assets/bash.png'},{text:'“Now,” says Fritz.',image:'assets/captain_fritz.png'},{text:'Bear points to the sun picture. “Morning.”',image:'assets/bear.png'},{text:'Nola points to the moon picture. “Night.”',image:'assets/nola.png'},{text:'Three letter tiles appear: S for sun, T for top, U for up.',image:'assets/alphabet-blocks.png'}],questions:[{prompt:'When do they put up the clock?',options:['Now','At night','Later'],answer:'Now'},{prompt:'Which picture means night?',options:['The moon','The sun','The book'],answer:'The moon'},{prompt:'What does WHEN ask about?',options:['Time','Identity','A thing'],answer:'Time'}],rewardPiece:{id:'time-board',name:'Morning and Night Board',icon:'🌅',area:'learning-room',lesson:'3-A'}},
    alphabetSong:Object.assign({},music),phonics:{letterUpper:'S T U',letterLower:'s t u',soundLabel:'/s/, /t/, short u',teacherCue:'Say: S—sun, T—top, U—up.',examples:[{word:'sun',icon:'☀️'},{word:'sit',icon:'🐾'},{word:'top',icon:'🔝'},{word:'ten',icon:'🔟'},{word:'up',icon:'⬆️'},{word:'under',icon:'⬇️'}],recognitionQuestion:{prompt:'Choose S T U.',options:['S T U','P Q R','V W X'],answer:'S T U'},lowercaseQuestion:{prompt:'Choose s t u.',options:['s t u','p q r','v w x'],answer:'s t u'},wordQuestion:{prompt:'Which set starts with S, T, U?',options:['sun, top, up','pig, queen, rabbit','van, web, box'],answer:'sun, top, up'},rewardPiece:{id:'stu-stones',name:'S T U Letter Stones',icon:'🔤',area:'learning-room',lesson:'3-A'}},
    reader1:{title:'Reader 1: When?',level:'First Reader',pages:[{text:'When do we start?',image:'assets/captain_fritz.png'},{text:'We start now.',image:'assets/bash.png'},{text:'The sun is up.',image:'assets/bear.png'},{text:'It is morning.',image:'assets/nola.png'},{text:'Later, the moon is up.',image:'assets/academy.png'}],check:{prompt:'When do they start?',options:['Now','At night','Tomorrow'],answer:'Now'},rewardPiece:{id:'time-reader',name:'Time Reader',icon:'📘',area:'learning-room',lesson:'3-A'}},
    reader2:{title:'Reader 2: Morning and Night',level:'Supported',pages:[{text:'In the morning, Fritz is at the Academy.',image:'assets/captain_fritz.png'},{text:'Bash can run and play.',image:'assets/bash.png'},{text:'Later, the sky is dark.',image:'assets/academy.png'},{text:'At night, the friends go home.',image:'assets/bear.png'},{text:'When is the sky dark? At night.',image:'assets/nola.png'}],check:{prompt:'When is the sky dark?',options:['At night','In the morning'],answer:'At night'},rewardPiece:{id:'sun-moon-markers',name:'Sun and Moon Markers',icon:'🌗',area:'learning-room',lesson:'3-A'}},
    build:{areaId:'learning-room',stage:4,title:'Build the Time Corner',requiredPieces:['when-clock','time-board','stu-stones','time-reader','sun-moon-markers'],completionMessage:'You built the Time Corner. You can understand a simple WHEN question.'},closingSong:Object.assign({},closing),completion:{xp:40,stars:1,unlocks:'3-B',message:'Lesson 7 complete! Lesson 8 is unlocked.'}
  });

  put('3-B',{
    id:'3-B',chapter:'Week 3',title:'Why? V W X',unlocked:false,reward:'Learning Room — Reason Station',buildArea:'learning-room',buildStage:5,canonicalLesson:8,
    objectives:{speaking:['Understand WHY as asking for a reason.','Use the supported frame “Because ___.”','Say V, W, X and their useful sounds.'],listening:['Match visible cause-and-effect situations.','Distinguish WHY from WHO/WHAT/WHERE/WHEN.','Hear /v/, /w/, and /ks/.'],reading:['Recognize V W X and v w x.','Read why and because in modeled sentences.','Read short supported cause/effect text.'],writing:['Identify and trace/copy V v, W w, X x.'],phonics:['V—van /v/.','W—web /w/.','X—box final /ks/.']},
    vocabulary:[{word:'why',display:'Why?',picture:'❓'},{word:'because',display:'Because ___.',picture:'💬'},{word:'wet',display:'It is wet.',picture:'💧'},{word:'rain',display:'It is raining.',picture:'🌧️'},{word:'open',display:'It is open.',picture:'🚪'},{word:'closed',display:'It is closed.',picture:'🔒'}],
    intro:[{speaker:'Captain Fritz',text:'WHY asks for a reason.'},{speaker:'Captain Fritz',text:'At first, we use reasons we can see.'},{speaker:'Captain Fritz',text:'Why is the path wet? Because it is raining.'},{speaker:'Captain Fritz',text:'Then we add V, W, X.'}],
    feelingChoices:[{id:'ready',label:'I am ready.',emoji:'⭐'},{id:'happy',label:'I am happy.',emoji:'😀'},{id:'okay',label:'I am okay.',emoji:'🙂'}],
    feelingsActivity:{title:'Find the Reason',instructions:'Look at the clue and choose the reason.',questions:[{emoji:'🌧️',prompt:'Why is the path wet?',options:['Because it is raining.','Because it is a dog.','Because there are three.'],answer:'Because it is raining.'},{emoji:'🔒',prompt:'Why can’t Bear go through the gate?',options:['Because it is closed.','Because it is morning.','Because this is Bash.'],answer:'Because it is closed.'},{emoji:'💡',prompt:'Why is the room bright?',options:['Because the light is on.','Because it is under the box.','Because it is Nola.'],answer:'Because the light is on.'}],rewardPiece:{id:'why-sign',name:'WHY Reason Sign',icon:'❓',area:'learning-room',lesson:'3-B'}},
    story:{title:'Why Is the Path Wet?',pages:[{text:'Bash steps outside and sees a wet path.',image:'assets/bash.png'},{text:'“Why is the path wet?” asks Bash.',image:'assets/bash.png'},{text:'Fritz points to the rain clouds.',image:'assets/captain_fritz.png'},{text:'“Because it is raining,” says Fritz.',image:'assets/captain_fritz.png'},{text:'Bear closes the garden gate so the room stays dry.',image:'assets/bear.png'},{text:'Inside, V, W, X tiles wait: van, web, box.',image:'assets/alphabet-blocks.png'}],questions:[{prompt:'Why is the path wet?',options:['Because it is raining','Because it is night','Because it is red'],answer:'Because it is raining'},{prompt:'Who asks why?',options:['Bash','Nola','Bear'],answer:'Bash'},{prompt:'What does WHY ask for?',options:['A reason','A location','A number'],answer:'A reason'}],rewardPiece:{id:'reason-board',name:'Cause and Reason Board',icon:'💬',area:'learning-room',lesson:'3-B'}},
    alphabetSong:Object.assign({},music),phonics:{letterUpper:'V W X',letterLower:'v w x',soundLabel:'/v/, /w/, /ks/',teacherCue:'Say: V—van, W—web, X—box. Notice X is often heard at the end of box.',examples:[{word:'van',icon:'🚐'},{word:'vet',icon:'🐾'},{word:'web',icon:'🕸️'},{word:'wet',icon:'💧'},{word:'box',icon:'📦'},{word:'six',icon:'6️⃣'}],recognitionQuestion:{prompt:'Choose V W X.',options:['V W X','S T U','Y Z'],answer:'V W X'},lowercaseQuestion:{prompt:'Choose v w x.',options:['v w x','s t u','y z'],answer:'v w x'},wordQuestion:{prompt:'Which set matches V, W, X sounds?',options:['van, web, box','sun, top, up','yellow, zebra, cat'],answer:'van, web, box'},rewardPiece:{id:'vwx-stones',name:'V W X Letter Stones',icon:'🔤',area:'learning-room',lesson:'3-B'}},
    reader1:{title:'Reader 1: Why Is It Wet?',level:'First Reader',pages:[{text:'The path is wet.',image:'assets/bash.png'},{text:'Why is it wet?',image:'assets/bash.png'},{text:'It is raining.',image:'assets/academy.png'},{text:'Because it is raining.',image:'assets/captain_fritz.png'},{text:'The friends go in.',image:'assets/bear.png'}],check:{prompt:'Why is the path wet?',options:['Because it is raining','Because it is red'],answer:'Because it is raining'},rewardPiece:{id:'reason-reader',name:'Reason Reader',icon:'📗',area:'learning-room',lesson:'3-B'}},
    reader2:{title:'Reader 2: Why Is It Closed?',level:'Supported',pages:[{text:'The gate is closed.',image:'assets/bear.png'},{text:'Nola asks, “Why?”',image:'assets/nola.png'},{text:'The rain is outside.',image:'assets/academy.png'},{text:'The gate is closed because the friends want the room dry.',image:'assets/captain_fritz.png'},{text:'WHY asks for a reason.',image:'assets/alphabet-blocks.png'}],check:{prompt:'What kind of answer follows WHY?',options:['A reason','A number','A name only'],answer:'A reason'},rewardPiece:{id:'because-card',name:'BECAUSE Card',icon:'💬',area:'learning-room',lesson:'3-B'}},
    build:{areaId:'learning-room',stage:5,title:'Build the Reason Station',requiredPieces:['why-sign','reason-board','vwx-stones','reason-reader','because-card'],completionMessage:'You built the Reason Station. You can recognize WHY and choose a visible reason.'},closingSong:Object.assign({},closing),completion:{xp:40,stars:1,unlocks:'3-C',message:'Lesson 8 complete! Lesson 9 is unlocked.'}
  });

  put('3-C',{
    id:'3-C',chapter:'Week 3',title:'Alphabet Question Mission Y Z',unlocked:false,reward:'Alphabet Foundation — Mission Complete',buildArea:'learning-room',buildStage:6,canonicalLesson:9,
    objectives:{speaking:['Use WHO, WHAT, WHERE, WHEN, WHY, HOW MANY, and WHICH in familiar contexts.','Answer simple yes/no questions and supported WH questions.','Say Y and Z and review A–Z.'],listening:['Identify which question word is being asked.','Follow mixed look/listen/point/choose/show directions.','Recognize all alphabet letters in cumulative play.'],reading:['Recognize Y Z and y z plus cumulative A–Z.','Read familiar high-frequency words from Lessons 1–8.','Read a controlled cumulative mission reader.'],writing:['Identify and trace/copy Y y and Z z; review letter formation as appropriate.'],phonics:['Y—yellow /y/.','Z—zebra /z/.','Review first-sound anchors A–Z.']},
    vocabulary:[{word:'who',display:'Who?',picture:'🐾'},{word:'what',display:'What?',picture:'📦'},{word:'where',display:'Where?',picture:'📍'},{word:'when',display:'When?',picture:'🕒'},{word:'why',display:'Why?',picture:'💬'},{word:'which',display:'Which?',picture:'👉'},{word:'how many',display:'How many?',picture:'🔢'}],
    intro:[{speaker:'Captain Fritz',text:'This is your Alphabet Question Mission!'},{speaker:'Captain Fritz',text:'You will finish Y and Z, then use every question skill you have learned.'},{speaker:'Captain Fritz',text:'Listen to the question word first. It tells you what kind of answer to give.'}],
    feelingChoices:[{id:'ready',label:'I am ready.',emoji:'⭐'},{id:'proud',label:'I am proud.',emoji:'😀'},{id:'okay',label:'I am okay.',emoji:'🙂'}],
    feelingsActivity:{title:'Question Mission',instructions:'Listen for the question word, then choose the kind of answer it needs.',questions:[{emoji:'🐾',prompt:'WHO is at the gate?',options:['Bash is at the gate.','The ball is red.','There are three.'],answer:'Bash is at the gate.'},{emoji:'📍',prompt:'WHERE is the ball?',options:['It is under the bench.','It is a ball.','Because it is raining.'],answer:'It is under the bench.'},{emoji:'🔢',prompt:'HOW MANY stars?',options:['There are three stars.','At night.','This is Nola.'],answer:'There are three stars.'},{emoji:'💬',prompt:'WHY is the path wet?',options:['Because it is raining.','The red one.','It is here.'],answer:'Because it is raining.'}],rewardPiece:{id:'question-wheel',name:'Question Word Wheel',icon:'🎡',area:'learning-room',lesson:'3-C'}},
    story:{title:'The Alphabet Question Mission',pages:[{text:'Fritz opens the final Alphabet Foundation mission.',image:'assets/captain_fritz.png'},{text:'Nola finds a yellow Y marker.',image:'assets/nola.png'},{text:'Bear finds a zebra Z card.',image:'assets/bear.png'},{text:'Bash follows clues using WHAT, WHO, and WHERE.',image:'assets/bash.png'},{text:'The team answers WHEN, WHY, WHICH, and HOW MANY clues.',image:'assets/academy.png'},{text:'All twenty-six alphabet blocks light up from A to Z.',image:'assets/alphabet-blocks.png'}],questions:[{prompt:'What color is the Y marker?',options:['Yellow','Blue','Red'],answer:'Yellow'},{prompt:'Who finds the Z card?',options:['Bear','Nola','Fritz'],answer:'Bear'},{prompt:'Why do the alphabet blocks light up?',options:['Because the team completes the mission','Because it is raining','Because the gate is closed'],answer:'Because the team completes the mission'}],rewardPiece:{id:'alphabet-arch',name:'A–Z Celebration Arch',icon:'🏛️',area:'learning-room',lesson:'3-C'}},
    alphabetSong:Object.assign({},music),phonics:{letterUpper:'Y Z + A–Z',letterLower:'y z + a–z',soundLabel:'/y/, /z/ + cumulative review',teacherCue:'Say: Y—yellow, Z—zebra. Then review A–Z with familiar sound anchors.',examples:[{word:'yellow',icon:'🟡'},{word:'yes',icon:'✅'},{word:'zebra',icon:'🦓'},{word:'zip',icon:'🤐'}],recognitionQuestion:{prompt:'Which letters finish the alphabet?',options:['Y Z','V W','S T'],answer:'Y Z'},lowercaseQuestion:{prompt:'Choose lowercase y and z.',options:['y z','v w','s t'],answer:'y z'},wordQuestion:{prompt:'Which pair starts with Y and Z?',options:['yellow and zebra','van and web','sun and top'],answer:'yellow and zebra'},rewardPiece:{id:'yz-stones',name:'Y Z Letter Stones',icon:'🔤',area:'learning-room',lesson:'3-C'}},
    reader1:{title:'Reader 1: Ask the Right Question',level:'Foundation Review',pages:[{text:'Who is this? This is Bash.',image:'assets/bash.png'},{text:'What is this? It is a ball.',image:'assets/bear.png'},{text:'Where is it? It is on the path.',image:'assets/academy.png'},{text:'When do we start? We start now.',image:'assets/captain_fritz.png'},{text:'Why is the path wet? Because it is raining.',image:'assets/nola.png'}],check:{prompt:'Which question asks for a reason?',options:['Why?','Who?','Where?'],answer:'Why?'},rewardPiece:{id:'question-reader-final',name:'Question Mission Reader',icon:'📚',area:'learning-room',lesson:'3-C'}},
    reader2:{title:'Reader 2: A–Z at Fritz Academy',level:'Supported Review',pages:[{text:'I see letters A to I.',image:'assets/alphabet-blocks.png'},{text:'I see letters J to R.',image:'assets/alphabet-blocks.png'},{text:'I see letters S to Z.',image:'assets/alphabet-blocks.png'},{text:'I can listen to a question.',image:'assets/captain_fritz.png'},{text:'I can choose an answer.',image:'assets/bash.png'},{text:'I am ready to learn how words work.',image:'assets/bear.png'}],check:{prompt:'What is the learner ready to do next?',options:['Learn how words work','Stop using letters','Forget the questions'],answer:'Learn how words work'},rewardPiece:{id:'foundation-badge',name:'Alphabet Foundation Badge',icon:'🏅',area:'learning-room',lesson:'3-C'}},
    build:{areaId:'learning-room',stage:6,title:'Complete the Alphabet Question Center',requiredPieces:['question-wheel','alphabet-arch','yz-stones','question-reader-final','foundation-badge'],completionMessage:'Alphabet Foundation complete: A–Z introduced, sounds begun, and core question words established. Next comes concentrated decoding and phonics.'},closingSong:Object.assign({},closing),completion:{xp:50,stars:2,unlocks:'3-D',message:'Lesson 9 complete! Alphabet Foundation Mission complete. Your decoding adventure is next.'}
  });
})();