/* Canonical Fritz Academy foundation runtime lessons 4-6. */
(function(){
  if(typeof LEVELS==='undefined'||!Array.isArray(LEVELS)) return;
  const music={title:'Fritz Academy Alphabet Song',rewardMessage:'Sing and review every letter you know!',assetPath:'assets/audio/alphabet-song.mp3',videoPath:'assets/video/alphabet-song.mp4'};
  const closing={title:'Fritz Academy Welcome Theme',assetPath:'assets/audio/fritz-academy-theme.mp3',videoPath:'assets/video/fritz-academy-theme.mp4',rewardMessage:'Celebrate your new question skill!'};
  const put=(id,lesson)=>{const i=LEVELS.findIndex(x=>x&&x.id===id); if(i>=0) LEVELS[i]=lesson; else LEVELS.push(lesson);};

  put('2-A',{
    id:'2-A',chapter:'Week 2',title:'Where Is It? J K L',unlocked:false,reward:'Learning Room — Location Corner',buildArea:'learning-room',buildStage:1,canonicalLesson:4,
    objectives:{speaking:['Ask and answer “Where is ___?”','Use here, there, in, on, under in short answers.','Say J, K, L and their useful sounds.'],listening:['Understand WHERE as asking about location.','Follow place an object in/on/under directions.','Hear /j/, /k/, /l/.'],reading:['Recognize J K L and j k l.','Read where, here, there, in, on with prior sight words.','Read controlled location sentences.'],writing:['Identify and trace/copy J j, K k, L l.'],phonics:['J—jam /j/.','K—kite /k/.','L—lamp /l/.']},
    vocabulary:[{word:'where',display:'Where is it?',picture:'❓'},{word:'here',display:'It is here.',picture:'📍'},{word:'there',display:'It is there.',picture:'👉'},{word:'in',display:'in the box',picture:'📥'},{word:'on',display:'on the box',picture:'⬆️'},{word:'under',display:'under the box',picture:'⬇️'}],
    intro:[{speaker:'Captain Fritz',text:'You know WHAT and WHO. Now we learn WHERE.'},{speaker:'Captain Fritz',text:'WHERE asks about a place or location.'},{speaker:'Captain Fritz',text:'Where is the builder key? Let’s look, listen, and find it.'}],
    feelingChoices:[{id:'ready',label:'I am ready.',emoji:'⭐'},{id:'happy',label:'I am happy.',emoji:'😀'},{id:'okay',label:'I am okay.',emoji:'🙂'}],
    feelingsActivity:{title:'Find the Place',instructions:'Choose the location that answers WHERE.',questions:[{emoji:'📦',prompt:'The key is inside the box. Where is the key?',options:['It is in the box.','It is on the box.','It is under the box.'],answer:'It is in the box.'},{emoji:'⬆️',prompt:'The book is on the bench. Where is the book?',options:['It is on the bench.','It is under the bench.','It is in the bench.'],answer:'It is on the bench.'},{emoji:'⬇️',prompt:'The ball is under the table. Where is the ball?',options:['It is under the table.','It is on the table.','It is here in a book.'],answer:'It is under the table.'}],rewardPiece:{id:'where-sign',name:'WHERE Sign',icon:'📍',area:'learning-room',lesson:'2-A'}},
    story:{title:'The Missing Builder Key',pages:[{text:'Fritz needs a key to open the Learning Room.',image:'assets/captain_fritz.png'},{text:'Bash looks on the bench.',image:'assets/bash.png'},{text:'Bear looks under a table.',image:'assets/bear.png'},{text:'Nola looks in a box.',image:'assets/nola.png'},{text:'“Here it is!” says Nola. The key is in the box.',image:'assets/nola.png'},{text:'The key tag shows J, K, and L: jam, kite, lamp.',image:'assets/alphabet-blocks.png'}],questions:[{prompt:'Where is the key?',options:['In the box','On the bench','Under the table'],answer:'In the box'},{prompt:'Who finds the key?',options:['Nola','Bear','Bash'],answer:'Nola'},{prompt:'Which question asks about location?',options:['Where is it?','Who is it?','What is it?'],answer:'Where is it?'}],rewardPiece:{id:'builder-key',name:'Learning Room Key',icon:'🔑',area:'learning-room',lesson:'2-A'}},
    alphabetSong:Object.assign({},music),
    phonics:{letterUpper:'J K L',letterLower:'j k l',soundLabel:'/j/, /k/, /l/',teacherCue:'Say: J—jam, K—kite, L—lamp.',examples:[{word:'jam',icon:'🫙'},{word:'jet',icon:'✈️'},{word:'kite',icon:'🪁'},{word:'key',icon:'🔑'},{word:'lamp',icon:'💡'},{word:'leg',icon:'🐾'}],recognitionQuestion:{prompt:'Choose J K L.',options:['J K L','G H I','M N O'],answer:'J K L'},lowercaseQuestion:{prompt:'Choose j k l.',options:['j k l','g h i','m n o'],answer:'j k l'},wordQuestion:{prompt:'Which set starts with J, K, L?',options:['jam, kite, lamp','goat, hat, igloo','map, nest, octopus'],answer:'jam, kite, lamp'},rewardPiece:{id:'jkl-stones',name:'J K L Letter Stones',icon:'🔤',area:'learning-room',lesson:'2-A'}},
    reader1:{title:'Reader 1: Where Is It?',level:'First Reader',pages:[{text:'Where is the key?',image:'assets/captain_fritz.png'},{text:'It is not on the bench.',image:'assets/bash.png'},{text:'It is not under the table.',image:'assets/bear.png'},{text:'It is in the box.',image:'assets/nola.png'},{text:'The key is here!',image:'assets/nola.png'}],check:{prompt:'Where is the key?',options:['In the box','Under the table','On the bench'],answer:'In the box'},rewardPiece:{id:'location-book',name:'Location Reader',icon:'📘',area:'learning-room',lesson:'2-A'}},
    reader2:{title:'Reader 2: Here and There',level:'Supported',pages:[{text:'Bash is here.',image:'assets/bash.png'},{text:'Bear is there.',image:'assets/bear.png'},{text:'The ball is on the path.',image:'assets/bear.png'},{text:'The book is in the room.',image:'assets/captain_fritz.png'},{text:'Where is Nola? Nola is here.',image:'assets/nola.png'}],check:{prompt:'Which word asks about a place?',options:['Where','Who','What'],answer:'Where'},rewardPiece:{id:'location-markers',name:'Here and There Markers',icon:'📍',area:'learning-room',lesson:'2-A'}},
    build:{areaId:'learning-room',stage:1,title:'Build the Location Corner',requiredPieces:['where-sign','builder-key','jkl-stones','location-book','location-markers'],completionMessage:'You built the Location Corner. You can ask WHERE and answer with a location.'},closingSong:Object.assign({},closing),completion:{xp:35,stars:1,unlocks:'2-B',message:'Lesson 4 complete! Lesson 5 is unlocked.'}
  });

  put('2-B',{
    id:'2-B',chapter:'Week 2',title:'How Many? M N O',unlocked:false,reward:'Learning Room — Counting Table',buildArea:'learning-room',buildStage:2,canonicalLesson:5,
    objectives:{speaking:['Answer “How many?” with a number and noun.','Use “I see ___.” and “There are ___.”','Say M, N, O and their useful sounds.'],listening:['Understand HOW MANY as asking for quantity.','Count 1–5 reliably and review toward 10 in game play.','Hear /m/, /n/, short /o/.'],reading:['Recognize M N O and m n o.','Read how, many, see, are with earlier words.','Read controlled counting sentences.'],writing:['Identify and trace/copy M m, N n, O o.'],phonics:['M—map /m/.','N—nest /n/.','O—octopus short /o/.']},
    vocabulary:[{word:'how many',display:'How many?',picture:'🔢'},{word:'one',display:'one',picture:'1️⃣'},{word:'two',display:'two',picture:'2️⃣'},{word:'three',display:'three',picture:'3️⃣'},{word:'four',display:'four',picture:'4️⃣'},{word:'five',display:'five',picture:'5️⃣'}],
    intro:[{speaker:'Captain Fritz',text:'WHERE asked us about place. Today HOW MANY asks us about quantity.'},{speaker:'Captain Fritz',text:'How many builder pieces do we need? Count with me.'},{speaker:'Captain Fritz',text:'We also add M, N, and O to our alphabet path.'}],
    feelingChoices:[{id:'ready',label:'I am ready.',emoji:'⭐'},{id:'happy',label:'I am happy.',emoji:'😀'},{id:'okay',label:'I am okay.',emoji:'🙂'}],
    feelingsActivity:{title:'Count and Answer',instructions:'Count the objects and choose the complete answer.',questions:[{emoji:'⭐⭐',prompt:'How many stars?',options:['There are two stars.','There are three stars.','There is one star.'],answer:'There are two stars.'},{emoji:'🐾🐾🐾',prompt:'How many paw prints?',options:['There are three paw prints.','There are four paw prints.','There are two paw prints.'],answer:'There are three paw prints.'},{emoji:'🍎🍎🍎🍎',prompt:'How many apples?',options:['There are four apples.','There are five apples.','There are three apples.'],answer:'There are four apples.'}],rewardPiece:{id:'counting-cards',name:'Counting Cards',icon:'🔢',area:'learning-room',lesson:'2-B'}},
    story:{title:'Five Pieces for the Table',pages:[{text:'Fritz opens a builder box.',image:'assets/captain_fritz.png'},{text:'Bash finds one map tile.',image:'assets/bash.png'},{text:'Bear finds two number blocks.',image:'assets/bear.png'},{text:'Nola finds two round markers.',image:'assets/nola.png'},{text:'“How many pieces?” asks Fritz. The friends count five.',image:'assets/captain_fritz.png'},{text:'The pieces show M, N, O: map, nest, octopus.',image:'assets/alphabet-blocks.png'}],questions:[{prompt:'How many builder pieces are there?',options:['Five','Four','Three'],answer:'Five'},{prompt:'Who asks “How many pieces?”',options:['Fritz','Bear','Bash'],answer:'Fritz'},{prompt:'What does HOW MANY ask about?',options:['Quantity','Identity','Location'],answer:'Quantity'}],rewardPiece:{id:'counting-table',name:'Counting Table',icon:'🧩',area:'learning-room',lesson:'2-B'}},
    alphabetSong:Object.assign({},music),phonics:{letterUpper:'M N O',letterLower:'m n o',soundLabel:'/m/, /n/, short o',teacherCue:'Say: M—map, N—nest, O—octopus.',examples:[{word:'map',icon:'🗺️'},{word:'moon',icon:'🌙'},{word:'nest',icon:'🪹'},{word:'nose',icon:'🐶'},{word:'octopus',icon:'🐙'},{word:'on',icon:'⬆️'}],recognitionQuestion:{prompt:'Choose M N O.',options:['M N O','J K L','P Q R'],answer:'M N O'},lowercaseQuestion:{prompt:'Choose m n o.',options:['m n o','j k l','p q r'],answer:'m n o'},wordQuestion:{prompt:'Which set starts with M, N, O?',options:['map, nest, octopus','jam, kite, lamp','pig, queen, rabbit'],answer:'map, nest, octopus'},rewardPiece:{id:'mno-stones',name:'M N O Letter Stones',icon:'🔤',area:'learning-room',lesson:'2-B'}},
    reader1:{title:'Reader 1: I See Three',level:'First Reader',pages:[{text:'I see one map.',image:'assets/bash.png'},{text:'I see two blocks.',image:'assets/bear.png'},{text:'I see three stars.',image:'assets/alphabet-blocks.png'},{text:'How many stars?',image:'assets/captain_fritz.png'},{text:'There are three stars.',image:'assets/nola.png'}],check:{prompt:'How many stars?',options:['Three','Two','Four'],answer:'Three'},rewardPiece:{id:'number-book',name:'Counting Reader',icon:'📗',area:'learning-room',lesson:'2-B'}},
    reader2:{title:'Reader 2: How Many?',level:'Supported',pages:[{text:'How many dogs are here?',image:'assets/bash.png'},{text:'Bash is here.',image:'assets/bash.png'},{text:'Bear is here.',image:'assets/bear.png'},{text:'Nola is here.',image:'assets/nola.png'},{text:'There are three Academy friends.',image:'assets/captain_fritz.png'}],check:{prompt:'How many Academy friends are named in the reader?',options:['Three','Two','Five'],answer:'Three'},rewardPiece:{id:'counting-basket',name:'Counting Basket',icon:'🧺',area:'learning-room',lesson:'2-B'}},
    build:{areaId:'learning-room',stage:2,title:'Build the Counting Table',requiredPieces:['counting-cards','counting-table','mno-stones','number-book','counting-basket'],completionMessage:'You built the Counting Table. You can understand and answer HOW MANY.'},closingSong:Object.assign({},closing),completion:{xp:35,stars:1,unlocks:'2-C',message:'Lesson 5 complete! Lesson 6 is unlocked.'}
  });

  put('2-C',{
    id:'2-C',chapter:'Week 2',title:'Which One? P Q R',unlocked:false,reward:'Learning Room — Choice Station',buildArea:'learning-room',buildStage:3,canonicalLesson:6,
    objectives:{speaking:['Answer “Which one?” by choosing and naming an option.','Use “This one.” and simple adjective+noun choices.','Say P, Q, R and their useful sounds.'],listening:['Understand WHICH as asking for a choice from known options.','Follow choose/show/give directions.','Hear /p/, /kw/, /r/.'],reading:['Recognize P Q R and p q r.','Read which, one, the with prior words.','Read controlled choice sentences.'],writing:['Identify and trace/copy P p, Q q, R r.'],phonics:['P—pig /p/.','Q—queen /kw/.','R—rabbit /r/.']},
    vocabulary:[{word:'which',display:'Which one?',picture:'❓'},{word:'one',display:'This one.',picture:'☝️'},{word:'choose',display:'Choose one.',picture:'👉'},{word:'show',display:'Show me.',picture:'👀'},{word:'give',display:'Give me the ___.',picture:'🐾'},{word:'the',display:'the red one',picture:'🔴'}],
    intro:[{speaker:'Captain Fritz',text:'Today we learn WHICH. WHICH asks us to choose from options.'},{speaker:'Captain Fritz',text:'Which one do we need: the red piece or the blue piece?'},{speaker:'Captain Fritz',text:'Choose, show, and answer. Then we add P, Q, R.'}],
    feelingChoices:[{id:'ready',label:'I am ready.',emoji:'⭐'},{id:'happy',label:'I am happy.',emoji:'😀'},{id:'okay',label:'I am okay.',emoji:'🙂'}],
    feelingsActivity:{title:'Which One?',instructions:'Choose the option that matches the clue.',questions:[{emoji:'🔴🔵',prompt:'Which one is red?',options:['The red one.','The blue one.','Both are blue.'],answer:'The red one.'},{emoji:'⬛🔺',prompt:'Which one is a triangle?',options:['The triangle.','The square.','Neither one.'],answer:'The triangle.'},{emoji:'📘⚽',prompt:'Which one is a book?',options:['This book.','This ball.','Both are balls.'],answer:'This book.'}],rewardPiece:{id:'which-sign',name:'WHICH Choice Sign',icon:'👉',area:'learning-room',lesson:'2-C'}},
    story:{title:'Choose the Right Builder Piece',pages:[{text:'Two builder pieces are on the table.',image:'assets/captain_fritz.png'},{text:'One piece is red. One piece is blue.',image:'assets/alphabet-blocks.png'},{text:'Fritz asks, “Which one fits the red gate?”',image:'assets/captain_fritz.png'},{text:'Bash points. “The red one.”',image:'assets/bash.png'},{text:'The piece fits, and the Choice Station lights up.',image:'assets/academy.png'},{text:'P, Q, R appear: pig, queen, rabbit.',image:'assets/alphabet-blocks.png'}],questions:[{prompt:'Which piece fits the red gate?',options:['The red one','The blue one','Neither one'],answer:'The red one'},{prompt:'Who chooses the piece?',options:['Bash','Bear','Nola'],answer:'Bash'},{prompt:'What does WHICH ask you to do?',options:['Choose','Count','Give a reason'],answer:'Choose'}],rewardPiece:{id:'choice-gate',name:'Choice Gate',icon:'🚪',area:'learning-room',lesson:'2-C'}},
    alphabetSong:Object.assign({},music),phonics:{letterUpper:'P Q R',letterLower:'p q r',soundLabel:'/p/, /kw/, /r/',teacherCue:'Say: P—pig, Q—queen, R—rabbit.',examples:[{word:'pig',icon:'🐷'},{word:'pen',icon:'🖊️'},{word:'queen',icon:'♛'},{word:'quilt',icon:'🧵'},{word:'rabbit',icon:'🐰'},{word:'red',icon:'🔴'}],recognitionQuestion:{prompt:'Choose P Q R.',options:['P Q R','M N O','S T U'],answer:'P Q R'},lowercaseQuestion:{prompt:'Choose p q r.',options:['p q r','m n o','s t u'],answer:'p q r'},wordQuestion:{prompt:'Which set starts with P, Q, R?',options:['pig, queen, rabbit','map, nest, octopus','sun, top, umbrella'],answer:'pig, queen, rabbit'},rewardPiece:{id:'pqr-stones',name:'P Q R Letter Stones',icon:'🔤',area:'learning-room',lesson:'2-C'}},
    reader1:{title:'Reader 1: Which One?',level:'First Reader',pages:[{text:'I see two pieces.',image:'assets/bash.png'},{text:'One is red.',image:'assets/alphabet-blocks.png'},{text:'One is blue.',image:'assets/alphabet-blocks.png'},{text:'Which one is red?',image:'assets/captain_fritz.png'},{text:'The red one.',image:'assets/bash.png'}],check:{prompt:'Which one is red?',options:['The red one','The blue one'],answer:'The red one'},rewardPiece:{id:'choice-reader',name:'Choice Reader',icon:'📘',area:'learning-room',lesson:'2-C'}},
    reader2:{title:'Reader 2: Choose and Show',level:'Supported',pages:[{text:'Fritz says, “Choose the book.”',image:'assets/captain_fritz.png'},{text:'Nola chooses the book.',image:'assets/nola.png'},{text:'Fritz says, “Show me the red one.”',image:'assets/captain_fritz.png'},{text:'Bear shows the red piece.',image:'assets/bear.png'},{text:'The friends can choose and show.',image:'assets/academy.png'}],check:{prompt:'What does Nola choose?',options:['The book','The ball','The hat'],answer:'The book'},rewardPiece:{id:'choice-buttons',name:'Choice Buttons',icon:'🔘',area:'learning-room',lesson:'2-C'}},
    build:{areaId:'learning-room',stage:3,title:'Build the Choice Station',requiredPieces:['which-sign','choice-gate','pqr-stones','choice-reader','choice-buttons'],completionMessage:'Week 2 complete. You can ask WHERE, HOW MANY, and WHICH, and you know A–R.'},closingSong:Object.assign({},closing),completion:{xp:40,stars:1,unlocks:'2-D',message:'Lesson 6 complete! Your next Academy challenge is unlocked.'}
  });
})();