/* Episode 6: The Three Paths — P/Q/R + WHICH */
(function(){if(typeof LEVELS==='undefined'||!Array.isArray(LEVELS))return;const l=LEVELS.find(x=>x&&x.id==='2-C');if(!l)return;
l.title='The Three Paths';l.episode={estimatedMinutes:20,beats:['hook','characterProblem','discoveryPlay','miniGame','storyTurn','readerMission','builderPayoff','tag'],miniGames:['choose the clue path','P/Q/R sign repair'],readerPurpose:'Read path signs and a short map note to choose the correct route.',builderPayoff:'Reach and restore the Choice Station on the far side of the grounds.',hook:'The repaired bridge ends at three paths. All three signs have been turned around.',tag:'At the restored station, an old Academy clock suddenly begins ticking. A card beneath it reads: BEFORE THE MUSIC BOX RINGS...'};
l.intro=[{speaker:'Tony',text:'Three paths. Easy. We take the middle one.'},{speaker:'Nola',text:'Why the middle one?'},{speaker:'Tony',text:'Because it is in the middle.'},{speaker:'Bash',text:'We have clues for a reason. We need to know WHICH path matches them.'},{speaker:'Rascal',text:'I vote for the path with the most mud.'},{speaker:'Bear',text:'I also—'},{speaker:'Bash',text:'No.'},{speaker:'Bear',text:'I had not finished.'},{speaker:'Bash',text:'You were going to say mud.'},{speaker:'Bear',text:'...maybe.'},{speaker:'Captain Fritz',text:'Use WHICH when choosing among known options. Help Bash read the P, Q and R signs before anyone chooses the mud.'}];
l.feelingsActivity.title='Which Path?';l.feelingsActivity.instructions='Compare the clues and choose THIS ONE, the matching sign, or the described path. Each correct choice turns a sign forward.';
l.story={title:'The Three Paths',pages:[{text:'Path P has a pig picture. Path Q has a queen picture. Path R has a rabbit picture.',image:'assets/alphabet-blocks.png'},{text:'The first clue says: Choose the path with R. “Which one?” asks Bash. The player chooses the rabbit path.',image:'assets/bash.png'},{text:'Halfway down it, they find another three-way marker: red, yellow and blue.',image:'assets/academy.png'},{text:'The note says: Choose the red one. Tony reaches for yellow. Nola points at the word RED.',image:'assets/nola.png'},{text:'Rascal finds a shortcut sign and begins turning it. Bear reaches to help. Bash catches both of them before the arrow moves.',image:'assets/bash.png'},{text:'“Maybe we should leave signs pointing where they actually point,” Bash says.',image:'assets/rascal.png'},{text:'The last choice shows three Academy symbols. The reader clue identifies the Choice Station symbol.',image:'assets/alphabet-blocks.png'},{text:'The player chooses the correct one. The trail opens into an old station with an Academy clock and Music Box stand.',image:'assets/academy.png'}],questions:[{prompt:'Which first path matches R?',options:['Rabbit path','Pig path','Queen path'],answer:'Rabbit path'},{prompt:'Which color does the note choose?',options:['Red','Yellow','Blue'],answer:'Red'},{prompt:'Who stops Rascal and Bear from turning the shortcut sign?',options:['Bash','Tony','Nola'],answer:'Bash'}],rewardPiece:{id:'pqr-choice-station',name:'Choice Station',icon:'🧭',area:'learning-room',lesson:'2-C'}};
l.phonics.teacherCue='Path signs use P—pig, Q—queen /kw/, R—rabbit. Hear the first sound and choose which sign matches the clue.';
l.reader1.title='Which Path Note';l.reader1.pages=[{text:'Which one?',image:'assets/bash.png'},{text:'Choose R.',image:'assets/alphabet-blocks.png'},{text:'The rabbit path.',image:'assets/alphabet-blocks.png'},{text:'This one.',image:'assets/bash.png'}];l.reader1.check={prompt:'Which path does the note choose?',options:['R','P','Q'],answer:'R'};
l.reader2.title='The Choice Station Sign';l.reader2.pages=[{text:'Choose the red one.',image:'assets/alphabet-blocks.png'},{text:'Choose this one.',image:'assets/bash.png'},{text:'This is the station.',image:'assets/academy.png'},{text:'We are here.',image:'assets/bash.png'}];l.reader2.check={prompt:'Which one does the sign choose?',options:['The red one','The blue one','The yellow one'],answer:'The red one'};
l.build.title='Restore the Choice Station';l.build.completionMessage='The Choice Station is restored. The team crossed the grounds by using clues instead of guessing.';
l.completion.unlocks='3-A';l.completion.message='Choice Station restored! The old clock begins ticking beside the Music Box. The Music Box Countdown is unlocked.';})();