/* Episode 4: The Lost Key Trail — J/K/L + WHERE */
(function(){if(typeof LEVELS==='undefined'||!Array.isArray(LEVELS))return;const l=LEVELS.find(x=>x&&x.id==='2-A');if(!l)return;
l.title='The Lost Key Trail';l.episode={estimatedMinutes:20,beats:['hook','characterProblem','discoveryPlay','miniGame','storyTurn','readerMission','builderPayoff','tag'],miniGames:['key-sign trail hunt','in-on-under location search'],readerPurpose:'Read a short trail card to locate the Builder key.',builderPayoff:'Recover the Builder key and unlock the next Welcome Garden construction area.',hook:'The J marker beyond the gate is shaped like a key, but the real Builder key is missing.',tag:'The recovered key opens a supply chest. Inside are bridge pieces—and several empty spaces where pieces should be.'};
l.intro=[{speaker:'Bash',text:'This little J sign points down the trail. There are more signs ahead.'},{speaker:'Tony',text:'Clearly a treasure map. As expedition leader, I recommend we follow me.'},{speaker:'Nola',text:'But where does it go? What if the trail leaves the Academy? What if the key is really gone?'},{speaker:'Rascal',text:'If we find treasure, I call the shiny part.'},{speaker:'Bear',text:'I call the snacks.'},{speaker:'Bash',text:'We are looking for the Builder key, not snacks. Look for J, K and L clues and tell us WHERE to search.'},{speaker:'Captain Fritz',text:'Good plan, Bash. WHERE helps us find a place. The player can help you search in, on and under things.'}];
l.feelingsActivity.title='Where Is the Key?';l.feelingsActivity.instructions='Search each scene. Choose IN, ON, UNDER, HERE or THERE to move Bash along the clue trail.';
l.story={title:'The Lost Key Trail',pages:[{text:'A J marker points toward the garden table. Bash finds a picture of jam under a small box.',image:'assets/bash.png'},{text:'“Where is the J clue?” asks Captain Fritz. It is under the box.',image:'assets/captain_fritz.png'},{text:'The K marker is on the fence beside a kite picture. Tony runs past it. Nola calls him back.',image:'assets/alphabet-blocks.png'},{text:'Rascal crawls under the bench looking for L. Bear starts to follow, but Bash stops his much bigger brother. “One dog under the bench is enough.”',image:'assets/bear.png'},{text:'Rascal pops out holding an L card with a lamp picture. “I found it! Also dust.”',image:'assets/rascal.png'},{text:'J, K and L point to the Builder shed. The final card says: LOOK IN THE RED BOX.',image:'assets/alphabet-blocks.png'},{text:'The player chooses IN. Bash opens the red box. The Builder key is there.',image:'assets/bash.png'},{text:'Tony nods. “Exactly where I expected it.” Nobody asks why he searched the fountain first.',image:'assets/academy.png'}],questions:[{prompt:'Where is the J clue?',options:['Under the box','On the roof','In the pond'],answer:'Under the box'},{prompt:'Where is the K marker?',options:['On the fence','Under the bench','In the box'],answer:'On the fence'},{prompt:'Where is the Builder key?',options:['In the red box','On the flag','Under Tony'],answer:'In the red box'}],rewardPiece:{id:'jkl-key-marker',name:'Builder Key Trail Marker',icon:'🗝️',area:'learning-room',lesson:'2-A'}};
l.phonics.teacherCue='Each trail sign has a sound clue: J—jam, K—kite, L—lamp. Match the sound, then use the sign to decide where to search.';
l.reader1.title='Trail Card: Where?';l.reader1.pages=[{text:'Look under the box.',image:'assets/bash.png'},{text:'J is here.',image:'assets/alphabet-blocks.png'},{text:'Look on the fence.',image:'assets/alphabet-blocks.png'},{text:'K is there.',image:'assets/alphabet-blocks.png'},{text:'Look under the bench.',image:'assets/rascal.png'},{text:'L is here.',image:'assets/alphabet-blocks.png'}];l.reader1.check={prompt:'Where is L?',options:['Under the bench','On the fence','In the red box'],answer:'Under the bench'};
l.reader2.title='The Red Box Note';l.reader2.pages=[{text:'Where is the key?',image:'assets/bash.png'},{text:'Look in the red box.',image:'assets/alphabet-blocks.png'},{text:'The key is in the box.',image:'assets/bash.png'},{text:'The key is here!',image:'assets/bash.png'}];l.reader2.check={prompt:'Where does the note say to look?',options:['In the red box','On the fence','Under the gate'],answer:'In the red box'};
l.build.title='Unlock the Builder Supply Chest';l.build.completionMessage='The Builder key is back. The supply chest opens—but some bridge pieces are missing.';l.completion.message='Key recovered! Inside the chest, Bash finds plans for a bridge with missing pieces.';})();