/* Episode 5: The Bridge With Missing Pieces — M/N/O + HOW/HOW MANY */
(function(){if(typeof LEVELS==='undefined'||!Array.isArray(LEVELS))return;const l=LEVELS.find(x=>x&&x.id==='2-B');if(!l)return;
l.title='The Bridge With Missing Pieces';l.episode={estimatedMinutes:20,beats:['hook','characterProblem','discoveryPlay','miniGame','storyTurn','readerMission','builderPayoff','tag'],miniGames:['count the bridge pieces','M/N/O supply sort'],readerPurpose:'Read the bridge plan to determine how many pieces are needed.',builderPayoff:'Repair the small garden bridge and open the route to the far side of the Academy grounds.',hook:'The supply chest contains a bridge plan, but several numbered spaces are empty.',tag:'Across the repaired bridge, the path splits into three directions marked P, Q and R.'};
l.intro=[{speaker:'Nola',text:'Pieces are missing. We cannot build half a bridge! Half a bridge is just a very organized way to fall in the grass.'},{speaker:'Tony',text:'No problem. We simply use every piece we have and begin.'},{speaker:'Bash',text:'No. First we count. The plan tells us HOW MANY pieces belong in each row.'},{speaker:'Rascal',text:'I can count pieces.'},{speaker:'Bear',text:'I can carry pieces.'},{speaker:'Bash',text:'And neither of you carries anything until we know where it goes.'},{speaker:'Captain Fritz',text:'That sounds like a leader with a plan. Help Bash count, sort M/N/O clues and build the bridge safely.'}];
l.feelingsActivity.title='How Many Pieces?';l.feelingsActivity.instructions='Count the visible bridge pieces and choose the matching number. Correct counts fill the plan.';
l.story={title:'The Bridge With Missing Pieces',pages:[{text:'The plan shows three rows. The first row needs three pieces. Bash counts: one, two, three.',image:'assets/bash.png'},{text:'Rascal slides a fourth piece toward the row. Bash catches it. “How many do we need?” Three—not four.',image:'assets/rascal.png'},{text:'An M card is attached to the map crate. N is beside a nest picture. O is beside an octopus picture.',image:'assets/alphabet-blocks.png'},{text:'The player sorts M—map, N—nest and O—octopus pieces into the correct supply bins.',image:'assets/alphabet-blocks.png'},{text:'Bear lifts a stack. “How many?” asks Bash. The player counts four. Bear carries exactly four.',image:'assets/bear.png'},{text:'Tony proposes skipping the last count because the bridge “looks bridge-shaped.” Nola strongly disagrees.',image:'assets/nola.png'},{text:'The plan says five final pegs. The player counts five. Bash checks them and gives Bear the go-ahead.',image:'assets/bash.png'},{text:'The little bridge is complete. Rascal tests one paw. Then two. It holds.',image:'assets/academy.png'}],questions:[{prompt:'How many pieces are needed in the first row?',options:['3','4','5'],answer:'3'},{prompt:'Who stops Rascal from adding an extra piece?',options:['Bash','Tony','Nola'],answer:'Bash'},{prompt:'How many final pegs does the plan need?',options:['5','2','1'],answer:'5'}],rewardPiece:{id:'mno-bridge',name:'Garden Bridge',icon:'🌉',area:'learning-room',lesson:'2-B'}};
l.phonics.teacherCue='Supply bins use M—map, N—nest, O—octopus. Hear the first sound, choose the bin, then count how many pieces are inside.';
l.reader1.title='Bridge Plan';l.reader1.pages=[{text:'I see three.',image:'assets/alphabet-blocks.png'},{text:'Put three here.',image:'assets/bash.png'},{text:'I see four.',image:'assets/alphabet-blocks.png'},{text:'Put four here.',image:'assets/bear.png'},{text:'I see five.',image:'assets/alphabet-blocks.png'},{text:'Put five here.',image:'assets/bash.png'}];l.reader1.check={prompt:'How many final pieces?',options:['Five','Three','One'],answer:'Five'};
l.reader2.title='Bash Checks the Bridge';l.reader2.pages=[{text:'How many?',image:'assets/bash.png'},{text:'I see three.',image:'assets/alphabet-blocks.png'},{text:'How many?',image:'assets/bash.png'},{text:'I see four.',image:'assets/alphabet-blocks.png'},{text:'The bridge is ready.',image:'assets/academy.png'}];l.reader2.check={prompt:'What is ready?',options:['The bridge','The flag','The gate'],answer:'The bridge'};
l.build.title='Finish the Garden Bridge';l.build.completionMessage='The bridge is complete because the team counted before building. Three paths wait on the far side.';l.completion.message='Bridge complete! Across it are three paths marked P, Q and R. Which one should the team take?';})();