/* Fritz Academy 51.20 — complete Lesson 1-D rebuild */
(function(){
'use strict';
const level=typeof findLevel==='function'?findLevel('1-D'):null;if(!level)return;
const reward=(id,name,image)=>({id,name,image,area:'welcome-garden',lesson:'1-D'});
Object.assign(level,{title:'The Question Garden',
story:{title:'The Mystery Map',pages:[
{text:'Captain Fritz and Tony find an old map beside the garden gate. “What is this?” asks Fritz. “It is a map,” says Tony.',scene:'map'},
{text:'Bear follows the map to a blue flower near the big tree. “Where is the blue flower?” he asks. Nola points to it.',scene:'flower'},
{text:'A bright butterfly lands on the flower. “Who can follow the butterfly?” asks Nola. Rascal runs after it.',scene:'butterfly'},
{text:'The Academy bell rings across the garden. “When do we meet at the fountain?” asks Tony. “When the bell rings,” says Fritz.',scene:'bell'},
{text:'The friends reach the fountain, but the watering can is gone. “Why is it missing?” asks Bear. They look for a clue.',scene:'missing'},
{text:'Bash returns with the watering can. “How do we help the garden?” asks Fritz. “We water the flowers together,” says Bash.',scene:'water'}],questions:[
{prompt:'What did Fritz and Tony find?',options:['A map','A hat','A ball'],answer:'A map'},
{prompt:'Where was the blue flower?',options:['Near the big tree','In the house','Under a bed'],answer:'Near the big tree'},
{prompt:'Who followed the butterfly?',options:['Rascal','Tony','No one'],answer:'Rascal'},
{prompt:'When do the friends meet?',options:['When the bell rings','Next year','At midnight'],answer:'When the bell rings'},
{prompt:'Why did they look for a clue?',options:['The watering can was missing','They were sleepy','It was raining'],answer:'The watering can was missing'},
{prompt:'How do they help the garden?',options:['They water the flowers together','They leave','They hide'],answer:'They water the flowers together'}],rewardPiece:reward('question-garden-sign','Question Garden Sign','assets/objects/question-sign-premium.svg')},
reader1:{title:'Reader 1: Six Questions in the Garden',pages:[
{text:'What did the friends find? They found a map.',scene:'map'},
{text:'Where was the flower? It was near the big tree.',scene:'flower'},
{text:'Who followed the butterfly? Rascal followed it.',scene:'butterfly'},
{text:'When did the friends meet? They met when the bell rang.',scene:'bell'},
{text:'Why did they search? The watering can was missing.',scene:'missing'},
{text:'How did they help? They watered the flowers together.',scene:'water'}],questions:[
{prompt:'Which word asks about a thing?',options:['What','Who','When'],answer:'What'},
{prompt:'Which word asks about a place?',options:['Where','Why','How'],answer:'Where'},
{prompt:'Which word asks about a person?',options:['Who','What','When'],answer:'Who'},
{prompt:'Which word asks about time?',options:['When','Where','Why'],answer:'When'},
{prompt:'Which word asks for a reason?',options:['Why','Who','What'],answer:'Why'},
{prompt:'Which word asks the way something is done?',options:['How','When','Where'],answer:'How'}],check:{prompt:'Which word asks for a reason?',options:['Why','Who','Where'],answer:'Why'},rewardPiece:reward('question-flower-bed','Question Flower Bed','assets/objects/question-flower-bed-premium.svg')},
reader2:{title:'Reader 2: The Garden Is Ready',pages:[
{text:'The map shows the Question Garden.',scene:'map'},
{text:'The blue flower grows near the tree.',scene:'flower'},
{text:'Rascal follows the butterfly to the fountain.',scene:'butterfly'},
{text:'The bell tells the friends when to meet.',scene:'bell'},
{text:'They search because the watering can is missing.',scene:'missing'},
{text:'Bash brings it back, and everyone waters the garden.',scene:'water'}],questions:[
{prompt:'What shows the garden?',options:['The map','The bell','The butterfly'],answer:'The map'},
{prompt:'Where does the flower grow?',options:['Near the tree','In the library','On the roof'],answer:'Near the tree'},
{prompt:'Who follows the butterfly?',options:['Rascal','Bear','Captain Fritz'],answer:'Rascal'},
{prompt:'When do the friends meet?',options:['When the bell rings','When they sleep','Next winter'],answer:'When the bell rings'},
{prompt:'Why do they search?',options:['The watering can is missing','They want a snack','The gate is blue'],answer:'The watering can is missing'},
{prompt:'How do they finish the garden?',options:['They water it together','They close it','They run away'],answer:'They water it together'}],check:{prompt:'How do they help the garden?',options:['They water it together','They hide','They sleep'],answer:'They water it together'},rewardPiece:reward('question-lantern','Question Garden Lantern','assets/objects/question-lantern-premium.svg')},
build:{areaId:'welcome-garden',stage:4,title:'Build the Question Garden',backgroundImage:'assets/environments/question-garden-premium.svg',requiredPieces:['question-garden-sign','question-flower-bed','question-lantern'],completionMessage:'You completed the Question Garden.'}});
function svgScene(kind){const scenes={
map:['#9bd8ff','#6fbd59','MAP','Captain Fritz','Tony','An old map waits beside the gate.'],
flower:['#bde9ff','#72c85f','BLUE FLOWER','Bear','Nola','A blue flower grows near the big tree.'],
butterfly:['#a9e3ff','#79c963','BUTTERFLY','Nola','Rascal','A butterfly flies toward the fountain.'],
bell:['#ffd9a8','#74bd59','BELL','Tony','Captain Fritz','The Academy bell rings in the garden.'],
missing:['#b9d9ef','#5ea34e','MISSING CAN','Bear','Nola','The watering can is gone.'],
water:['#9ee4ff','#68bf55','WATERING CAN','Bash','Captain Fritz','The friends water the flowers together.']};
const s=scenes[kind]||scenes.map;const [sky,grass,obj,left,right,note]=s;
const pup=(x,color,name)=>`<g transform="translate(${x} 145)"><ellipse cx="0" cy="105" rx="55" ry="72" fill="${color}" stroke="#17324d" stroke-width="7"/><circle cx="0" cy="35" r="53" fill="${color}" stroke="#17324d" stroke-width="7"/><path d="M-45 5l-24-38 43 20M45 5l24-38-43 20" fill="${color}" stroke="#17324d" stroke-width="7"/><circle cx="-17" cy="28" r="7"/><circle cx="17" cy="28" r="7"/><ellipse cx="0" cy="50" rx="13" ry="10" fill="#222"/><path d="M-12 66q12 14 24 0" fill="none" stroke="#222" stroke-width="6"/><rect x="-58" y="150" width="116" height="34" rx="15" fill="#fff8d4" stroke="#17324d" stroke-width="4"/><text x="0" y="173" text-anchor="middle" font-family="Arial" font-size="19" font-weight="700" fill="#102342">${name}</text></g>`;
let object='';if(kind==='map')object='<path d="M430 290l95-25 80 30-95 26z" fill="#f6dc77" stroke="#714f22" stroke-width="7"/><path d="M478 278v36M548 277v34" stroke="#b58a37" stroke-width="5"/>';
if(kind==='flower')object='<path d="M520 330v-95" stroke="#287b3a" stroke-width="12"/><circle cx="520" cy="220" r="24" fill="#368cff"/><circle cx="495" cy="235" r="24" fill="#4aa0ff"/><circle cx="545" cy="235" r="24" fill="#4aa0ff"/><circle cx="520" cy="250" r="24" fill="#368cff"/><circle cx="520" cy="235" r="15" fill="#ffd54c"/>';
if(kind==='butterfly')object='<g transform="translate(520 225)"><ellipse cx="-28" cy="0" rx="30" ry="42" fill="#ff8ac5"/><ellipse cx="28" cy="0" rx="30" ry="42" fill="#ffc84a"/><rect x="-5" y="-35" width="10" height="70" rx="5" fill="#333"/></g>';
if(kind==='bell')object='<path d="M480 275q40-85 80 0l20 38h-120z" fill="#f4bd35" stroke="#7f5a10" stroke-width="7"/><circle cx="520" cy="315" r="12" fill="#7f5a10"/>';
if(kind==='missing')object='<rect x="445" y="245" width="150" height="95" rx="16" fill="#fff7cf" stroke="#b54a3b" stroke-width="7" stroke-dasharray="12 10"/><text x="520" y="302" text-anchor="middle" font-family="Arial" font-size="26" font-weight="800" fill="#b54a3b">MISSING</text>';
if(kind==='water')object='<path d="M470 245h90v80h-90z" fill="#69b7df" stroke="#245a77" stroke-width="7"/><path d="M560 260q70 0 65 55" fill="none" stroke="#245a77" stroke-width="14"/><path d="M485 245q15-50 60 0" fill="none" stroke="#245a77" stroke-width="12"/><path d="M635 315q20 15 0 34q-20-19 0-34" fill="#43a8ff"/>';
return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1040 520"><rect width="1040" height="520" fill="${sky}"/><circle cx="875" cy="82" r="50" fill="#ffe078"/><path d="M0 295Q220 235 430 295T1040 280V520H0Z" fill="${grass}"/><path d="M470 520l45-185h50l55 185z" fill="#d8c090"/><g opacity=".9"><circle cx="160" cy="270" r="72" fill="#3d843f"/><rect x="150" y="270" width="20" height="100" fill="#775031"/><circle cx="900" cy="270" r="72" fill="#3d843f"/><rect x="890" y="270" width="20" height="100" fill="#775031"/></g>${pup(250,'${left.includes('Fritz')?'#f5f0e8':left==='Tony'?'#f4f1e8':left==='Bear'?'#d69a43':left==='Nola'?'#65402f':'#f1b84c'}','${left}')}${pup(790,'${right.includes('Fritz')?'#f5f0e8':right==='Tony'?'#f4f1e8':right==='Bear'?'#d69a43':right==='Nola'?'#65402f':right==='Rascal'?'#f1b84c':'#d89735'}','${right}')}${object}<rect x="270" y="18" width="500" height="58" rx="20" fill="#fff8dc" stroke="#174ea6" stroke-width="5"/><text x="520" y="56" text-anchor="middle" font-family="Arial" font-size="28" font-weight="800" fill="#102342">${note}</text></svg>`)}`;}
function clear(){document.querySelectorAll('.l420,.l419-overlay,.l419-builder,.l418-overlay,.l418-builder,.l4stable').forEach(n=>n.remove());}
function styles(){if(document.getElementById('l420css'))return;const s=document.createElement('style');s.id='l420css';s.textContent='.l420{position:fixed;inset:0;z-index:900000;background:#071426e8;display:grid;place-items:center;font-family:Arial}.l420book{width:min(1080px,97vw);height:min(820px,96vh);background:#fffdf4;border:6px solid #102342;border-radius:22px;overflow:hidden;display:grid;grid-template-rows:auto 1fr auto}.l420head{text-align:center;padding:12px;background:#fff1b7;border-bottom:3px solid #174ea6;font-size:27px;font-weight:900;color:#102342}.l420main{display:grid;grid-template-rows:minmax(390px,1fr) auto;min-height:0}.l420main img{width:calc(100% - 36px);height:calc(100% - 18px);margin:12px 18px 6px;object-fit:contain;border:4px solid #174ea6;border-radius:16px;background:#dff2ff}.l420text{padding:8px 30px 14px;text-align:center;font-size:28px;line-height:1.25;font-weight:800;color:#102342}.l420foot{display:flex;justify-content:center;gap:20px;padding:12px;border-top:3px solid #102342}.l420foot button{padding:11px 25px;border:3px solid #102342;border-radius:10px;font-size:21px;font-weight:900;background:#fff}.l420foot .next{background:#ffc63d}.l420builder{width:min(1240px,98vw);height:min(820px,96vh);background:#fff;border:6px solid #f6c744;border-radius:22px;overflow:hidden;display:grid;grid-template-rows:auto 1fr auto}.l420bmain{display:grid;grid-template-columns:250px 1fr;min-height:0}.l420tray{padding:12px;background:#eef5ff;border-right:3px solid #174ea6}.l420piece{width:100%;display:flex;align-items:center;gap:10px;padding:8px;margin-bottom:10px;border:3px solid #9bb0c7;border-radius:12px;background:#fff;font-weight:800}.l420piece img{width:72px;height:72px;object-fit:contain}.l420stage{position:relative;background:url("assets/environments/question-garden-premium.svg") center/cover no-repeat}.l420placed{position:absolute;width:150px;height:150px;transform:translate(-50%,-50%)}.l420placed img{width:100%;height:100%;object-fit:contain}.l420bfoot{display:flex;justify-content:center;gap:12px;padding:10px;border-top:3px solid #174ea6}.l420bfoot button{padding:10px 18px;border:3px solid #102342;border-radius:10px;font-weight:900}.l420bfoot .done{background:#ffc63d}';document.head.appendChild(s);}
function render(host,section,index,next,label){styles();clear();const p=section.pages[index],text=host.lessonEngine.replaceName(p.text||'');const ov=document.createElement('div');ov.className='l420';ov.innerHTML=`<section class="l420book"><header class="l420head">${section.title} — Page ${index+1} of ${section.pages.length}</header><main class="l420main"><img alt="Illustrated story scene"><div class="l420text"></div></main><footer class="l420foot"><button class="read">Read Aloud</button><button class="next">${label}</button></footer></section>`;ov.querySelector('img').src=svgScene(p.scene);ov.querySelector('.l420text').textContent=text;ov.querySelector('.read').onclick=()=>host.lessonEngine.speakText(text);ov.querySelector('.next').onclick=()=>{ov.remove();next()};document.body.appendChild(ov);}
if(window.StoryEngine)StoryEngine.prototype.showPage=function(){if(!this.lesson||this.lesson.id!=='1-D')return;if(this.pageIndex>=this.story.pages.length){this.startQuestions();return}const last=this.pageIndex===this.story.pages.length-1;render(this,this.story,this.pageIndex,()=>{this.pageIndex++;this.showPage()},last?'Story Questions':'Next Page')};
if(window.ReaderEngine)ReaderEngine.prototype.showPage=function(){if(!this.lesson||this.lesson.id!=='1-D')return;if(this.pageIndex>=this.reader.pages.length){this.startCheck();return}const last=this.pageIndex===this.reader.pages.length-1;render(this,this.reader,this.pageIndex,()=>{this.pageIndex++;this.showPage()},last?'Reader Questions':'Next Page')};
if(window.BuilderEngine)BuilderEngine.prototype.showBuilder=function(){if(!(this.lessonEngine&&this.lessonEngine.lesson&&this.lessonEngine.lesson.id==='1-D'))return;styles();clear();const pieces=[['question-garden-sign','Question Garden Sign','assets/objects/question-sign-premium.svg'],['question-flower-bed','Question Flower Bed','assets/objects/question-flower-bed-premium.svg'],['question-lantern','Question Garden Lantern','assets/objects/question-lantern-premium.svg']];const ov=document.createElement('div');ov.className='l420';ov.innerHTML='<section class="l420builder"><header class="l420head">Build the Question Garden</header><main class="l420bmain"><aside class="l420tray"></aside><div class="l420stage"></div></main><footer class="l420bfoot"><button class="later">Keep Building Later</button><button class="done">Finish This Build</button></footer></section>';const tray=ov.querySelector('.l420tray'),stage=ov.querySelector('.l420stage');let selected=null,placed={};pieces.forEach(p=>{const b=document.createElement('button');b.className='l420piece';b.innerHTML=`<img src="${p[2]}"><span>${p[1]}</span>`;b.onclick=()=>selected=p;tray.appendChild(b)});stage.onclick=e=>{if(!selected)return;const r=stage.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*100,y=(e.clientY-r.top)/r.height*100;placed[selected[0]]={x,y};const d=document.createElement('div');d.className='l420placed';d.style.left=x+'%';d.style.top=y+'%';d.innerHTML=`<img src="${selected[2]}">`;stage.querySelector(`[data-id="${selected[0]}"]`)?.remove();d.dataset.id=selected[0];stage.appendChild(d);selected=null};ov.querySelector('.later').onclick=()=>ov.remove();ov.querySelector('.done').onclick=()=>{if(Object.keys(placed).length<3){alert('Place all three earned pieces in the garden.');return}ov.remove();this.completeBuild()};document.body.appendChild(ov)};
})();