/* Fritz Academy 53.4 — Lesson 6 six-kite adventure + workshop */
(function(){
'use strict';
const level=typeof findLevel==='function'?findLevel('2-B'):null;if(!level)return;
const reward=(id,name,icon)=>({id,name,icon,area:'kite-workshop',lesson:'2-B'});
Object.assign(level,{
 title:'The Kite Chase',
 story:{title:'The Kite Chase',pages:[
  {text:'Bear finds a bright kite beside the Academy path. He lifts it carefully and calls, “Look what I found!”'},
  {text:'Rascal races over. “Let me try it!” he says. Before Bear can answer, Rascal grabs for the string.'},
  {text:'Bear runs to keep the kite safe. Rascal chases him around the fountain. Neither puppy sees that they are about to crash.'},
  {text:'Nola sees the danger. She runs to get Bash and Tony. “They need help now,” she says.'},
  {text:'Bash steps between Bear and Rascal just before they collide. He holds out one paw and says, “Stop. We can solve this.”'},
  {text:'Tony pushes up his glasses. “Of course we can. We will make six kites—one for Bear, Rascal, Nola, Bash, and {studentName}, plus one large kite for Captain Fritz.”'},
  {text:'Captain Fritz arrives and asks, “What will you need? Who will do each job? How will you work safely?” The puppies and {studentName} make a plan.'},
  {text:'Tony explains each step. Bash hands out the pieces. Nola checks the plan. Bear and Rascal work side by side instead of chasing.'},
  {text:'Soon five student-and-puppy kites and one large captain’s kite rise above the Academy. Captain Fritz asks, “What changed?” Bear says, “We worked together.”'}
 ],questions:[
  {prompt:'Why does Rascal chase Bear?',options:['He wants to try the kite','He wants an orange','He is looking for Tony'],answer:'He wants to try the kite'},
  {prompt:'Who sees that Bear and Rascal may crash?',options:['Nola','Captain Fritz','No one'],answer:'Nola'},
  {prompt:'How does Bash help?',options:['He stops them before they collide','He hides the kite','He runs away'],answer:'He stops them before they collide'},
  {prompt:'What solution does Tony suggest?',options:['Build six kites','Throw the kite away','Lock the Academy'],answer:'Build six kites'},
  {prompt:'What do Bear and Rascal learn?',options:['Work together and share','Run faster','Never build anything'],answer:'Work together and share'}
 ],rewardPiece:reward('kite-workshop-sign','Kite Workshop Sign','🪧')},
 reader1:{title:'Reader 1: Stop the Chase',level:'Easy',pages:[
  {text:'Bear has a kite.'},{text:'Rascal wants the kite.'},{text:'Bear runs.'},{text:'Rascal runs after Bear.'},{text:'Nola gets Bash.'},{text:'Bash says, “Stop!”'}
 ],check:{prompt:'Who stops the chase?',options:['Bash','Tony','Bear'],answer:'Bash'},rewardPiece:reward('safe-path-marker','Safe Path Marker','🛑')},
 reader2:{title:'Reader 2: Six Kites',level:'Easy Plus',pages:[
  {text:'Tony has a plan.'},{text:'Bash brings the sticks.'},{text:'Nola checks the paper.'},{text:'Bear and Rascal tie the string.'},{text:'They make five small kites.'},{text:'They make one big kite for Captain Fritz.'}
 ],check:{prompt:'How many kites do they make?',options:['Six','Five','Three'],answer:'Six'},rewardPiece:reward('six-kite-display','Six-Kite Display','🪁')},
 build:{areaId:'kite-workshop',stage:1,title:'Tony’s Six-Kite Workshop',requiredPieces:['kite-workshop-sign','safe-path-marker','six-kite-display'],completionMessage:'You helped the Academy team build six kites safely.'},
 completion:{xp:45,stars:2,unlocks:'2-C',message:'Lesson 6 complete! You solved the kite problem and built six kites.'}
});

function css(){if(document.getElementById('fa534css'))return;const s=document.createElement('style');s.id='fa534css';s.textContent=`
.fa534{position:fixed;inset:0;z-index:1000020;background:#071426ef;display:grid;place-items:center;font-family:Arial,sans-serif;padding:10px}.fa534box{width:min(1140px,98vw);height:min(790px,96vh);background:#fffdf2;border:6px solid #f4c542;border-radius:24px;overflow:hidden;display:grid;grid-template-rows:auto 1fr auto}.fa534head{background:linear-gradient(#fff4b8,#efd05e);padding:12px 18px;text-align:center;color:#102342;border-bottom:4px solid #174ea6}.fa534head h1{margin:0}.fa534work{background:url('assets/academy.png') center/cover no-repeat;display:grid;grid-template-columns:240px 1fr;gap:16px;padding:18px}.fa534guide{background:#102342e9;color:white;border:5px solid #ffe28a;border-radius:20px;padding:12px;text-align:center;display:grid;grid-template-rows:auto 1fr auto}.fa534guide img{width:175px;height:225px;object-fit:contain;background:white;border-radius:14px;margin:auto;animation:bob534 1.8s ease-in-out infinite}@keyframes bob534{50%{transform:translateY(-6px)}}.fa534guide p{font-size:16px;font-weight:800;line-height:1.3}.fa534stage{background:#ffffffed;border:5px solid #174ea6;border-radius:22px;padding:14px;display:grid;grid-template-rows:auto 1fr auto}.fa534kites{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;align-items:center}.fa534kite{height:225px;border:4px dashed #c49a24;border-radius:16px;background:#f8fbff;position:relative;display:grid;place-items:center}.fa534kite b{position:absolute;top:6px;color:#102342}.fa534shape{width:120px;height:150px;position:relative}.fa534part{position:absolute;opacity:.14;transition:.25s}.fa534part.on{opacity:1;transform:scale(1.03)}.fa534sail{left:20px;top:15px;width:80px;height:100px;background:linear-gradient(135deg,#ffcf4e 50%,#56b7ff 50%);clip-path:polygon(50% 0,100% 45%,50% 100%,0 45%)}.fa534cross{left:57px;top:15px;width:6px;height:100px;background:#6d4c2d}.fa534cross:after{content:'';position:absolute;width:76px;height:6px;background:#6d4c2d;left:-35px;top:44px}.fa534tail{left:58px;top:112px;width:4px;height:45px;background:#7a4b2a}.fa534parts{display:flex;justify-content:center;gap:10px;flex-wrap:wrap;margin-top:8px}.fa534btn{padding:10px 16px;border:3px solid #102342;border-radius:12px;background:#fff;font-size:16px;font-weight:900;cursor:pointer}.fa534msg{text-align:center;font-size:18px;font-weight:900;color:#102342;margin-top:8px}.fa534foot{background:#102342;text-align:center;padding:10px}.fa534finish{display:none;padding:12px 26px;border:3px solid white;border-radius:12px;background:#ffc63d;font-size:20px;font-weight:900}
`;document.head.appendChild(s)}
if(window.BuilderEngine){const old=BuilderEngine.prototype.showBuilder;BuilderEngine.prototype.showBuilder=function(){if((this.lesson&&this.lesson.id)!=='2-B'&&this.lessonEngine?.levelId!=='2-B')return old.call(this);css();document.querySelectorAll('.fa534').forEach(n=>n.remove());const names=['Bear','Rascal','Nola','Bash',this.lessonEngine.studentName||'Student','Captain Fritz'];let kite=0,step=0;const steps=['sail','cross','tail'];const o=document.createElement('div');o.className='fa534';o.innerHTML=`<section class="fa534box"><header class="fa534head"><h1>Tony’s Six-Kite Workshop</h1><p>Build one kite for each teammate and one large kite for Captain Fritz.</p></header><main class="fa534work"><aside class="fa534guide"><h2>Tony</h2><img src="assets/tony.png" alt="Tony"><p>Tony gives the directions. Bash hands over each piece. Choose the parts in order.</p></aside><section class="fa534stage"><div class="fa534kites">${names.map((n,i)=>`<div class="fa534kite"><b>${n}</b><div class="fa534shape"><span class="fa534part fa534sail"></span><span class="fa534part fa534cross"></span><span class="fa534part fa534tail"></span></div></div>`).join('')}</div><div class="fa534parts"><button class="fa534btn" data-part="sail">1. Paper Sail</button><button class="fa534btn" data-part="cross">2. Cross Sticks</button><button class="fa534btn" data-part="tail">3. Tail & String</button></div><div class="fa534msg">Tony: Start with the paper sail for ${names[0]}.</div></section></main><footer class="fa534foot"><button class="fa534finish">Fly the Six Kites ➜</button></footer></section>`;const kites=[...o.querySelectorAll('.fa534kite')],msg=o.querySelector('.fa534msg'),finish=o.querySelector('.fa534finish');o.querySelectorAll('.fa534btn').forEach(b=>b.onclick=()=>{const wanted=steps[step],picked=b.dataset.part;if(picked!==wanted){msg.textContent=`Tony: Not yet. Choose ${wanted==='sail'?'the paper sail':wanted==='cross'?'the cross sticks':'the tail and string'}.`;return;}kites[kite].querySelector('.fa534'+wanted).classList.add('on');step++;if(step===steps.length){kite++;step=0;if(kite===kites.length){msg.textContent='All six kites are ready! Bear and Rascal worked together.';finish.style.display='inline-block';}else msg.textContent=`Bash hands over the next pieces. Build the kite for ${names[kite]}.`;}else msg.textContent=`Good. Now choose ${steps[step]==='cross'?'the cross sticks':'the tail and string'}.`;});finish.onclick=()=>{o.remove();this.finish();};document.body.appendChild(o);};}
window.FRITZ_LESSON6_KITE='53.4';
})();