class MiniGameEngine {
  constructor(scene,lessonEngine){this.scene=scene;this.lessonEngine=lessonEngine;this.lesson=null;this.onComplete=null;this.pairs=[];this.answerOrder=[];this.matched=new Set();this.selectedPrompt=null;this.feedback='';}
  start(lesson,onComplete){this.lesson=lesson;this.onComplete=onComplete;this.matched=new Set();this.selectedPrompt=null;this.feedback='';this.pairs=this.buildPairs(lesson);if(this.pairs.length<2){this.finish();return;}this.answerOrder=this.shuffle(this.pairs.map((_,i)=>i));this.lessonEngine.setSection('mini-game');this.renderBoard();}
  buildPairs(lesson){const result=[],seen=new Set(),sources=[lesson&&lesson.feelingsActivity&&lesson.feelingsActivity.questions,lesson&&lesson.story&&lesson.story.questions];for(const source of sources){if(!Array.isArray(source))continue;for(const q of source){if(!q||!q.prompt||!q.answer)continue;const answer=String(q.answer).trim();if(!answer||seen.has(answer))continue;result.push({prompt:String(q.prompt).trim(),answer});seen.add(answer);if(result.length>=3)return result;}}return result;}
  shuffle(values){const c=values.slice();for(let i=c.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[c[i],c[j]]=[c[j],c[i]];}if(c.length>1&&c.every((v,i)=>v===i))c.push(c.shift());return c;}
  gameLabel(){const specs=this.lesson&&this.lesson.episode&&this.lesson.episode.miniGames;return Array.isArray(specs)&&specs.length?String(specs[0]).replace(/[-_]/g,' ').replace(/\b\w/g,l=>l.toUpperCase()):'Mission Match';}
  renderBoard(){if(this.matched.size>=this.pairs.length){this.renderWin();return;}const objects=[],title=this.scene.add.text(0,-245,this.gameLabel(),{fontSize:'28px',fontStyle:'bold',color:'#102342',align:'center',wordWrap:{width:700}}).setOrigin(.5);objects.push(title);objects.push(this.scene.add.text(0,-208,`MINI-GAME • ${this.matched.size}/${this.pairs.length} matches`,{fontSize:'17px',fontStyle:'bold',color:'#46566f'}).setOrigin(.5));if(this.feedback)objects.push(this.scene.add.text(0,225,this.feedback,{fontSize:'17px',fontStyle:'bold',color:this.feedback.startsWith('Match')?'#2f7d32':'#b5462d',align:'center',wordWrap:{width:680}}).setOrigin(.5));const ys=[-125,-5,115];this.pairs.forEach((pair,index)=>{if(this.matched.has(index))return;const selected=this.selectedPrompt===index;const card=this.scene.add.text(-205,ys[index],pair.prompt,{fontSize:'18px',fontStyle:'bold',color:'#102342',backgroundColor:selected?'#fff1ad':'#ffffff',padding:{x:12,y:10},align:'center',wordWrap:{width:280}}).setOrigin(.5).setInteractive({useHandCursor:true});card.on('pointerdown',()=>{this.selectedPrompt=index;this.feedback='Choose its match.';this.renderBoard();});objects.push(card);});this.answerOrder.forEach((pairIndex,slotIndex)=>{if(this.matched.has(pairIndex))return;const pair=this.pairs[pairIndex],card=this.scene.add.text(205,ys[slotIndex],pair.answer,{fontSize:'18px',fontStyle:'bold',color:'#174ea6',backgroundColor:'#eef4ff',padding:{x:12,y:10},align:'center',wordWrap:{width:280}}).setOrigin(.5).setInteractive({useHandCursor:true});card.on('pointerdown',()=>this.chooseAnswer(pairIndex));objects.push(card);});objects.push(this.scene.add.text(-205,-175,'CLUES',{fontSize:'16px',fontStyle:'bold',color:'#46566f'}).setOrigin(.5),this.scene.add.text(205,-175,'MATCHES',{fontSize:'16px',fontStyle:'bold',color:'#46566f'}).setOrigin(.5));this.scene.panels.open(objects,{width:840,height:620});}
  chooseAnswer(pairIndex){if(this.selectedPrompt===null){this.feedback='Choose a clue first.';this.renderBoard();return;}if(this.selectedPrompt===pairIndex){this.matched.add(pairIndex);this.selectedPrompt=null;this.feedback='Match made!';this.renderBoard();return;}this.feedback='Not that one — try another match.';this.renderBoard();}
  renderWin(){const title=this.scene.add.text(0,-75,'Mini-Game Complete!',{fontSize:'36px',fontStyle:'bold',color:'#2f7d32'}).setOrigin(.5),body=this.scene.add.text(0,15,`All ${this.pairs.length} clues matched.`,{fontSize:'25px',fontStyle:'bold',color:'#102342',align:'center'}).setOrigin(.5),next=this.scene.panels.makeButton(0,115,'Keep Going',()=>this.finish());this.scene.panels.open([title,body,next],{width:650,height:340});}
  finish(){const cb=this.onComplete;this.onComplete=null;if(typeof cb==='function')cb();}
}
window.MiniGameEngine=MiniGameEngine;