/* Fritz Academy Reader Engine v58 */
class ReaderEngine {
  constructor(scene,lessonEngine){this.scene=scene;this.lessonEngine=lessonEngine;this.questionEngine=new QuestionEngine(scene,lessonEngine);this.lesson=null;this.reader=null;this.readerKey='';this.pageIndex=0;this.onComplete=null;}
  start(lesson,readerKey,onComplete){this.lesson=lesson;this.readerKey=readerKey;this.reader=lesson&&lesson[readerKey];this.pageIndex=0;this.onComplete=onComplete;if(!this.reader||!Array.isArray(this.reader.pages)||!this.reader.pages.length){this.scene.panels.message('Reader Missing','This lesson does not contain a complete reader.');return;}this.lessonEngine.stopMedia();this.lessonEngine.setSection(readerKey);this.showPage();}
  normalizePage(page){if(typeof page==='string')return{text:page,image:''};return{text:page&&page.text?page.text:'',image:page&&page.image?page.image:''};}
  showPage(){if(this.pageIndex>=this.reader.pages.length){if(window.FRITZ_SCENE_PRESENTATION)window.FRITZ_SCENE_PRESENTATION.close();this.startCheck();return;}const page=this.normalizePage(this.reader.pages[this.pageIndex]);const text=this.lessonEngine.replaceName(page.text);const label=this.readerKey==='reader1'?'📘 READER 1':'📗 READER 2';if(window.FRITZ_SCENE_PRESENTATION){window.FRITZ_SCENE_PRESENTATION.open({badge:label,title:this.reader.title||label,pageIndex:this.pageIndex,total:this.reader.pages.length,text,pageImage:page.image,nextLabel:this.pageIndex===this.reader.pages.length-1?'Reader Questions →':'Next Reader Page →',onRead:()=>this.lessonEngine.speakText(text),onNext:()=>{this.lessonEngine.stopMedia();this.pageIndex++;this.showPage();}});return;}this.scene.panels.message(label,text);}
  startCheck(){const questions=Array.isArray(this.reader.questions)?this.reader.questions:(this.reader.check?[this.reader.check]:[]);if(!questions.length){this.finishReader();return;}this.questionEngine.start({title:this.readerKey==='reader1'?'Reader 1 Comprehension':'Reader 2 Comprehension',questions,successMessage:'Correct!',retryMessage:'Look back at the reader and try again.',onComplete:()=>this.finishReader()});}
  finishReader(){const finish=()=>{const cb=this.onComplete;this.onComplete=null;if(typeof cb==='function')cb();};if(this.reader.rewardPiece){this.lessonEngine.rewardPiece(this.reader.rewardPiece,'You completed this reader!',finish);return;}finish();}
}
window.ReaderEngine=ReaderEngine;