/* Fritz Academy Scene Presentation v59
   Stable cast refs + student avatar + real Academy props. */
(function(){
  const ART_RAW='https://raw.githubusercontent.com/pamelajlang01-FritzAcademy/fritz-academy/recovery-v50-1-exact/';
  const CAST_RAW='https://raw.githubusercontent.com/pamelajlang01-FritzAcademy/fritz-academy/92f549ac9a3d312c73e6d9ec2e3331575d8aabaa/';
  const CAST={
    'Captain Fritz':{src:CAST_RAW+'assets/characters/approved/captain-fritz/nautical-idle.webp',scale:0.98},
    'Bash':{src:CAST_RAW+'assets/characters/approved/bash/sweatsuit-idle.webp',scale:1.15},
    'Bear':{src:CAST_RAW+'assets/characters/approved/bear/sweatsuit-idle.webp',scale:0.84},
    'Nola':{src:CAST_RAW+'assets/characters/approved/nola/sweatsuit-idle.webp',scale:0.98},
    'Tony':{src:CAST_RAW+'assets/characters/approved/tony/sweatsuit-idle.webp',scale:0.63},
    'Rascal':{src:'assets/characters/approved/rascal/approved-hero.svg',scale:0.82}
  };
  const ENV={
    academy:ART_RAW+'assets/environments/academy_front.png',gate:ART_RAW+'assets/environments/academy_gate.png',garden:ART_RAW+'assets/environments/welcome_garden.png',
    workshop:ART_RAW+'assets/environments/builder_workshop.png',stream:ART_RAW+'assets/environments/stream.png',bridge:ART_RAW+'assets/environments/bridge.png',
    reading:ART_RAW+'assets/environments/reading_room.png',classroom:ART_RAW+'assets/environments/classroom_beginner.png',hallway:ART_RAW+'assets/environments/hallway.png'
  };
  const PROP={
    bench:ART_RAW+'assets/objects/reading_bench.png',tree:ART_RAW+'assets/objects/garden_tree.png',flowers:ART_RAW+'assets/objects/welcome_flowers.png',
    path:ART_RAW+'assets/objects/stone_path.png',fence:ART_RAW+'assets/objects/garden_fence.png',flag:ART_RAW+'assets/objects/academy_flag.png',
    books:ART_RAW+'assets/objects/book_cart.png',shelf:ART_RAW+'assets/objects/book_shelf.png',steps:ART_RAW+'assets/objects/paw_print_stepping_stones.png'
  };
  const esc=s=>encodeURIComponent(s).replace(/'/g,'%27').replace(/%20/g,' ');
  function avatarSvg(skin,hair,shirt,style){
    const hairPath=style===1?'<path d="M42 47q18-35 60-18 22 9 21 39-17-22-38-22-23 0-43 20z" fill="'+hair+'"/>':style===2?'<circle cx="82" cy="40" r="27" fill="'+hair+'"/><circle cx="57" cy="49" r="15" fill="'+hair+'"/><circle cx="107" cy="49" r="15" fill="'+hair+'"/>':'<path d="M43 58q3-44 40-44 41 0 42 46-17-19-41-19-24 0-41 17z" fill="'+hair+'"/>';
    const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="170" height="300" viewBox="0 0 170 300"><ellipse cx="85" cy="286" rx="50" ry="10" fill="#0b223b" opacity=".2"/><g stroke="#132f54" stroke-width="4" stroke-linejoin="round"><path d="M57 161h56l17 108H99l-14-63-14 63H40z" fill="#6d7e94"/><path d="M47 119q38-25 76 0l-8 82H55z" fill="${shirt}"/><path d="M62 120l23 27 23-27" fill="#fff"/><path d="M85 147v33"/><path d="M79 147h12l8 22-14 12-14-12z" fill="#e8b83d"/><circle cx="85" cy="78" r="44" fill="${skin}"/>${hairPath}<circle cx="68" cy="81" r="4" fill="#3a2418" stroke="none"/><circle cx="102" cy="81" r="4" fill="#3a2418" stroke="none"/><path d="M70 100q15 12 30 0" fill="none" stroke="#6b352a" stroke-linecap="round"/><path d="M54 136L28 201M116 136l26 65" fill="none" stroke="${skin}" stroke-width="16" stroke-linecap="round"/><circle cx="85" cy="132" r="10" fill="#173f72"/><path d="M80 128l5-10 5 10-5 10z" fill="#f5c646" stroke="none"/></g></svg>`;
    return 'data:image/svg+xml;charset=UTF-8,'+esc(svg);
  }
  const AVATARS={
    explorer1:avatarSvg('#f1c7a5','#5a321f','#173f72',0),explorer2:avatarSvg('#8d5a3c','#21170f','#6b3fa0',1),explorer3:avatarSvg('#dca57f','#3a2418','#2f7b56',2),
    explorer4:avatarSvg('#f2d2ba','#d7a35a','#b34e75',1),explorer5:avatarSvg('#70432d','#15100d','#d0702f',0),explorer6:avatarSvg('#c88962','#2a1710','#3869ad',2)
  };
  window.FRITZ_STUDENT_AVATARS=AVATARS;
  function environmentFor(opts){const s=(String(opts.title||'')+' '+String(opts.text||'')+' '+String(opts.pageImage||'')).toLowerCase();if(s.includes('workshop')||s.includes('kite')&&(s.includes('make')||s.includes('build')))return ENV.workshop;if(s.includes('pond')||s.includes('fish')||s.includes('windmill')||s.includes('weather'))return ENV.stream;if(s.includes('bridge'))return ENV.bridge;if(s.includes('classroom')||s.includes('desk'))return ENV.classroom;if(s.includes('hall'))return ENV.hallway;if(s.includes('gate'))return ENV.gate;return ENV.garden;}
  function injectStyles(){if(document.getElementById('fa-scene59-style'))return;const s=document.createElement('style');s.id='fa-scene59-style';s.textContent=`
.fa-scene58{position:fixed;inset:0;z-index:10100;background:rgba(4,14,29,.94);display:flex;align-items:center;justify-content:center;font-family:Arial,sans-serif;color:#102342}.fa-scene58 *{box-sizing:border-box}.fa-scene58-card{width:min(1180px,96vw);height:min(820px,94vh);background:#fff8e8;border:5px solid #0f3564;border-radius:24px;overflow:hidden;display:flex;flex-direction:column;box-shadow:0 20px 70px rgba(0,0,0,.55)}.fa-scene58-head{height:76px;display:flex;align-items:center;gap:18px;padding:10px 18px;background:linear-gradient(#fff3b8,#f4cf61);border-bottom:4px solid #0f4f9e;flex:0 0 auto}.fa-scene58-badge{background:#123b72;color:white;border-radius:999px;padding:10px 18px;font-weight:900;font-size:18px;white-space:nowrap}.fa-scene58-title{font-size:25px;font-weight:900;flex:1;text-align:center}.fa-scene58-page{font-size:16px;font-weight:800;color:#334e73}.fa-scene58-stage{position:relative;flex:1;min-height:0;overflow:hidden;background-size:cover;background-position:center;background-repeat:no-repeat}.fa-scene58-cast{position:absolute;left:3%;right:3%;bottom:-1%;height:82%;display:flex;align-items:flex-end;justify-content:center;gap:1.2%;pointer-events:none;z-index:3}.fa-scene58-char{height:67%;max-width:20%;object-fit:contain;object-position:center bottom;filter:drop-shadow(0 9px 8px rgba(0,0,0,.32));transform-origin:center bottom;animation:faIdle59 3.2s ease-in-out infinite}.fa-scene58-student{height:66%;max-width:18%;object-fit:contain;filter:drop-shadow(0 9px 8px rgba(0,0,0,.3));z-index:3}.fa-scene58-prop{position:absolute;object-fit:contain;filter:drop-shadow(0 7px 5px rgba(0,0,0,.28));z-index:2;pointer-events:none}.fa-scene58-prop.p0{width:15%;left:10%;bottom:2%}.fa-scene58-prop.p1{width:14%;right:11%;bottom:4%}.fa-scene58-prop.p2{width:12%;left:45%;bottom:0}@keyframes faIdle59{0%,100%{translate:0 0}50%{translate:0 -5px}}.fa-scene58-journal{min-height:162px;background:#fffaf0;border-top:4px solid #102f5e;padding:16px 24px 14px;display:flex;flex-direction:column;justify-content:center}.fa-scene58-text{font-size:27px;line-height:1.3;font-weight:800;text-align:center;max-width:1020px;margin:0 auto 12px}.fa-scene58-actions{display:flex;justify-content:center;gap:18px}.fa-scene58-btn{border:3px solid #153c70;border-radius:14px;padding:10px 23px;background:white;color:#102342;font-size:18px;font-weight:900;cursor:pointer}.fa-scene58-btn.next{background:#f5c646}@media(max-width:760px){.fa-scene58-card{width:100vw;height:100vh;border-radius:0;border:0}.fa-scene58-page{display:none}.fa-scene58-text{font-size:21px}.fa-scene58-char,.fa-scene58-student{height:58%;max-width:25%}}
`;document.head.appendChild(s);}
  function castFor(text,pageImage){const t=String(text||'').toLowerCase(),names=[];Object.keys(CAST).forEach(name=>{if(t.includes(name.toLowerCase()))names.push(name);});const p=String(pageImage||'').toLowerCase();['bash','bear','nola','tony','rascal'].forEach(n=>{if(p.includes(n)){const name=n[0].toUpperCase()+n.slice(1);if(!names.includes(name))names.push(name);}});if(p.includes('captain_fritz')&&!names.includes('Captain Fritz'))names.push('Captain Fritz');return names.slice(0,4);}
  function propsFor(text){const t=String(text||'').toLowerCase(),arr=[];if(t.includes('bench'))arr.push(PROP.bench);if(t.includes('tree'))arr.push(PROP.tree);if(t.includes('flower'))arr.push(PROP.flowers);if(t.includes('path'))arr.push(PROP.path);if(t.includes('fence'))arr.push(PROP.fence);if(t.includes('flag'))arr.push(PROP.flag);if(t.includes('book'))arr.push(PROP.books);if(t.includes('shelf'))arr.push(PROP.shelf);if(t.includes('step'))arr.push(PROP.steps);if(t.includes('apple')||t.includes('basket')){const b=`<svg xmlns="http://www.w3.org/2000/svg" width="220" height="170"><g stroke="#603819" stroke-width="6"><path d="M42 72h136l-18 76H60z" fill="#b9783a"/><path d="M70 75q40-70 80 0" fill="none"/><g fill="#d83b32" stroke="#74251f">${[[72,68],[105,60],[137,69],[91,84],[123,86]].map(([x,y])=>`<circle cx="${x}" cy="${y}" r="22"/>`).join('')}</g></g></svg>`;arr.push('data:image/svg+xml;charset=UTF-8,'+esc(b));}return arr.slice(0,3);}
  function close(){document.querySelectorAll('.fa-scene58').forEach(n=>n.remove());}
  function open(opts){injectStyles();close();const root=document.createElement('div');root.className='fa-scene58';const card=document.createElement('div');card.className='fa-scene58-card';const head=document.createElement('div');head.className='fa-scene58-head';const badge=document.createElement('div');badge.className='fa-scene58-badge';badge.textContent=opts.badge||'ACADEMY STORY';const title=document.createElement('div');title.className='fa-scene58-title';title.textContent=opts.title||'';const page=document.createElement('div');page.className='fa-scene58-page';page.textContent=`Page ${opts.pageIndex+1} of ${opts.total}`;head.append(badge,title,page);const stage=document.createElement('div');stage.className='fa-scene58-stage';stage.style.backgroundImage=`url('${opts.background||environmentFor(opts)}')`;propsFor(opts.text).forEach((src,i)=>{const im=document.createElement('img');im.className='fa-scene58-prop p'+i;im.src=src;stage.appendChild(im);});const cast=document.createElement('div');cast.className='fa-scene58-cast';const active=(typeof getSave==='function'?getSave():null);if(active&&active.studentName){const av=document.createElement('img');av.className='fa-scene58-student';av.src=AVATARS[active.avatar]||AVATARS.explorer1;av.alt=active.studentName;av.title=active.studentName;cast.appendChild(av);}castFor(opts.text,opts.pageImage).forEach(name=>{const spec=CAST[name],img=document.createElement('img');img.className='fa-scene58-char';img.src=spec.src;img.alt=name;img.title=name;img.style.transform=`scale(${spec.scale})`;img.onerror=()=>{img.style.display='none';};cast.appendChild(img);});stage.appendChild(cast);const journal=document.createElement('div');journal.className='fa-scene58-journal';const txt=document.createElement('div');txt.className='fa-scene58-text';txt.textContent=opts.text||'';const actions=document.createElement('div');actions.className='fa-scene58-actions';const read=document.createElement('button');read.className='fa-scene58-btn';read.textContent='🔊 Read Aloud';read.onclick=()=>opts.onRead&&opts.onRead();const next=document.createElement('button');next.className='fa-scene58-btn next';next.textContent=opts.nextLabel||'Next Page →';next.onclick=()=>{close();opts.onNext&&opts.onNext();};actions.append(read,next);journal.append(txt,actions);card.append(head,stage,journal);root.appendChild(card);document.body.appendChild(root);}
  window.FRITZ_SCENE_PRESENTATION={open,close,cast:CAST,environments:ENV,avatars:AVATARS};
})();