/* Fritz Academy 52.3 — classroom-ready fifth adventure (2-A) */
(function(){
'use strict';
const level=typeof findLevel==='function'?findLevel('2-A'):null;if(!level)return;
const reward=(id,name,icon)=>({id,name,icon,area:'academy-world',lesson:'2-A'});
const cast=['Captain Fritz','Tony','Bash','Bear','Rascal','Nola'];
function scene(title,note,focus){
 const colors={'Captain Fritz':'#f6f1e8',Tony:'#e7e2d7',Bash:'#bd7a35',Bear:'#d59a45',Rascal:'#f0b84b',Nola:'#684536'};
 const pups=cast.map((name,i)=>{const x=115+i*162,y=i%2?275:250;return `<g transform="translate(${x} ${y})"><ellipse cx="0" cy="62" rx="42" ry="53" fill="${colors[name]}" stroke="#17324d" stroke-width="6"/><circle cx="0" cy="12" r="39" fill="${colors[name]}" stroke="#17324d" stroke-width="6"/><path d="M-33-8l-18-29 34 15M33-8l18-29-34 15" fill="${colors[name]}" stroke="#17324d" stroke-width="6"/><circle cx="-12" cy="8" r="5"/><circle cx="12" cy="8" r="5"/><ellipse cx="0" cy="23" rx="8" ry="6"/><rect x="-53" y="112" width="106" height="25" rx="11" fill="#fff8d4"/><text x="0" y="130" text-anchor="middle" font-family="Arial" font-size="13" font-weight="700">${name}</text></g>`}).join('');
 const letters=['A','B','C','D','E','F','G','H'].map((l,i)=>`<g transform="translate(${170+i*95} 425)"><circle r="35" fill="${i%2?'#ffd05a':'#76c8ff'}" stroke="#17324d" stroke-width="5"/><text y="13" text-anchor="middle" font-family="Arial" font-size="38" font-weight="900">${l}</text></g>`).join('');
 return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1040 520"><rect width="1040" height="520" fill="#a9ddff"/><circle cx="900" cy="75" r="48" fill="#ffe071"/><path d="M0 305Q210 245 430 300T1040 285V520H0Z" fill="#82c76b"/><path d="M430 520l55-220h70l65 220z" fill="#d9bf8c"/><rect x="170" y="24" width="700" height="72" rx="22" fill="#fff8da" stroke="#174ea6" stroke-width="5"/><text x="520" y="57" text-anchor="middle" font-family="Arial" font-size="27" font-weight="900" fill="#102342">${title}</text><text x="520" y="84" text-anchor="middle" font-family="Arial" font-size="18" font-weight="700" fill="#174ea6">${note}</text>${pups}${letters}<circle cx="${115+cast.indexOf(focus)*162}" cy="${cast.indexOf(focus)%2?275:250}" r="67" fill="none" stroke="#ffd23f" stroke-width="9" stroke-dasharray="14 9"/></svg>`)}`;
}
Object.assign(level,{
 title:'The Alphabet Gate Adventure',chapter:'Week 2',buildArea:'academy-world',buildStage:5,
 objectives:{speaking:['Answer feelings and activity questions in complete sentences.','Use who, what, where, when, why, and how.'],reading:['Review letters A through H in connected stories.','Use story evidence to answer questions.'],phonics:['Review A, B, C, D, E, F, G, and H sounds.']},
 feelingChoices:[{id:'happy',label:'I am happy.',emoji:'😀'},{id:'excited',label:'I am excited.',emoji:'🤩'},{id:'fine',label:'I am fine.',emoji:'🙂'},{id:'tired',label:'I am tired.',emoji:'😴'},{id:'sad',label:'I am sad.',emoji:'😢'},{id:'nervous',label:'I am nervous.',emoji:'😟'}],
 feelingsActivity:{title:'How Are You Today?',instructions:'Choose a feeling and say the complete sentence.',questions:[{emoji:'😀',prompt:'How does this face feel?',options:['I am happy.','I am tired.','I am sad.'],answer:'I am happy.'},{emoji:'😴',prompt:'How does this face feel?',options:['I am excited.','I am tired.','I am fine.'],answer:'I am tired.'},{emoji:'😟',prompt:'How does this face feel?',options:['I am nervous.','I am happy.','I am excited.'],answer:'I am nervous.'}]},
 story:{title:'The Locked Alphabet Gate',pages:[
  {text:'Captain Fritz calls Tony, Bash, Bear, Rascal, Nola, and {studentName} to the old Academy gate. Eight letter stones are missing.',image:scene('The Academy Team Meets','Who is at the gate? Everyone!','Captain Fritz')},
  {text:'Tony finds A beside an apple and B beside a blue ball. “What did you find?” asks Fritz. “A and B,” Tony answers.',image:scene('A and B','What did Tony find?','Tony')},
  {text:'Bear sees C near a cat sign and D near a red door. “Where are C and D?” asks Nola. “Near the garden door,” says Bear.',image:scene('C and D','Where are the letters?','Bear')},
  {text:'Bash carries E from the egg-shaped fountain and F from the flower path. “How did you move them?” asks Rascal. “Carefully,” says Bash.',image:scene('E and F','How did Bash move them?','Bash')},
  {text:'Nola discovers G under the green gate, while Rascal finds H beside a happy-face flag. “Why were they hidden?” Tony asks.',image:scene('G and H','Why were the stones hidden?','Nola')},
  {text:'The bell rings when all eight stones are in order. The gate opens, and the friends see a wide field where {studentName} can build a growing Academy.',image:scene('The Gate Opens','When does the gate open?','Rascal')}
 ],questions:[
  {prompt:'Who comes to the old Academy gate?',options:['The whole Academy team','Only Tony','No one'],answer:'The whole Academy team'},
  {prompt:'What does Tony find?',options:['A and B','G and H','A map'],answer:'A and B'},
  {prompt:'Where are C and D?',options:['Near the garden door','Under a bed','In the sky'],answer:'Near the garden door'},
  {prompt:'How does Bash move E and F?',options:['Carefully','Loudly','By throwing them'],answer:'Carefully'},
  {prompt:'When does the gate open?',options:['When all eight stones are in order','At midnight','Before they arrive'],answer:'When all eight stones are in order'}
 ],rewardPiece:reward('alphabet-gate','Alphabet Gate','🚪')},
 alphabetSong:{title:'Alphabet Review A–H',assetPath:'assets/video/alphabet-song.mp4',videoPath:'assets/video/alphabet-song.mp4',rewardMessage:'You reviewed A through H.'},
 phonics:{letterUpper:'A B C D E F G H',letterLower:'a b c d e f g h',soundLabel:'A through H review',teacherCue:'Say each letter and one word: apple, ball, cat, dog, egg, flower, gate, happy.',examples:[{word:'apple',icon:'🍎'},{word:'ball',icon:'⚽'},{word:'cat',icon:'🐱'},{word:'dog',icon:'🐶'},{word:'egg',icon:'🥚'},{word:'flower',icon:'🌼'},{word:'gate',icon:'🚪'},{word:'happy',icon:'😀'}],recognitionQuestion:{prompt:'Which set shows the letters reviewed today?',options:['A B C D E F G H','I J K L','W X Y Z'],answer:'A B C D E F G H'},lowercaseQuestion:{prompt:'Which begins with lowercase a?',options:['apple','ball','cat'],answer:'apple'},wordQuestion:{prompt:'Which word begins with H?',options:['happy','gate','flower'],answer:'happy'}},
 reader1:{title:'Reader 1: Six Good Questions',pages:[
  {text:'Who found A and B? Tony found them.',image:scene('WHO','Who asks about a person.','Tony')},
  {text:'What did Bear find? Bear found C and D.',image:scene('WHAT','What asks about a thing.','Bear')},
  {text:'Where were G and H? They were near the green gate.',image:scene('WHERE','Where asks about a place.','Nola')},
  {text:'When did the gate open? It opened when the letters were in order.',image:scene('WHEN','When asks about time.','Captain Fritz')},
  {text:'Why did the friends search? They wanted to open the gate.',image:scene('WHY','Why asks for a reason.','Rascal')},
  {text:'How did they succeed? They worked together.',image:scene('HOW','How asks the way.','Bash')}
 ],questions:[{prompt:'Which word asks about a person?',options:['Who','Where','When'],answer:'Who'},{prompt:'Which word asks about a place?',options:['Where','Why','How'],answer:'Where'},{prompt:'Which word asks for a reason?',options:['Why','What','Who'],answer:'Why'}],check:{prompt:'Which word asks the way something happens?',options:['How','When','Where'],answer:'How'},rewardPiece:reward('question-fountain','Question Fountain','⛲')},
 reader2:{title:'Reader 2: Our Academy Begins',pages:[
  {text:'The wide field belongs to the Academy team and {studentName}.',image:scene('A New Building Field','The Academy can grow here.','Captain Fritz')},
  {text:'Tony plans a reading corner. Bash marks a safe building path.',image:scene('Friends Make Plans','Tony and Bash work together.','Bash')},
  {text:'Bear chooses a place for the alphabet gate. Nola plans flowers around it.',image:scene('A Place for Every Piece','Bear and Nola choose carefully.','Bear')},
  {text:'Rascal carries the Question Fountain to an open spot.',image:scene('The Question Fountain','Rascal helps the Academy grow.','Rascal')},
  {text:'Every reward from the first four adventures can return to this same field.',image:scene('Old Rewards Return','Nothing earned is lost.','Nola')},
  {text:'The Academy will look different for every student because each student chooses where the pieces belong.',image:scene('Your Academy','You decide where each piece goes.','Tony')}
 ],questions:[{prompt:'Who chooses where the Academy pieces belong?',options:['The student','A stranger','No one'],answer:'The student'},{prompt:'What can return to the field?',options:['Rewards from earlier adventures','Only one flower','Nothing'],answer:'Rewards from earlier adventures'},{prompt:'Why can every Academy look different?',options:['Each student places the pieces','The pieces disappear','The gate is locked'],answer:'Each student places the pieces'}],check:{prompt:'What is the field becoming?',options:['The student’s Academy','A parking lot','An empty road'],answer:'The student’s Academy'},rewardPiece:reward('academy-friendship-tree','Academy Friendship Tree','🌳')},
 build:{areaId:'academy-world',stage:5,title:'Build Your Academy',requiredPieces:['alphabet-gate','question-fountain','academy-friendship-tree'],completionMessage:'Your Academy saved every placed piece.'},
 completion:{xp:40,stars:2,unlocks:'2-B',message:'Adventure complete! Your Academy is saved, and Level 2-B is unlocked.'}
});

if(typeof LessonEngine!=='undefined'){
 const oldOpen=LessonEngine.prototype.showMissionOpening,oldGreeting=LessonEngine.prototype.showGreeting;
 const feelings=[['😀','Happy','I am happy.'],['🤩','Excited','I am excited.'],['🙂','Fine','I am fine.'],['😴','Tired','I am tired.'],['😢','Sad','I am sad.'],['😟','Nervous','I am nervous.']];
 const acts=[['⚽','Played','I played.'],['📖','Read','I read.'],['📺','Watched TV','I watched TV.'],['✏️','Studied','I studied.'],['🍎','Ate','I ate.'],['🛏️','Slept','I slept.'],['🎮','Played a game','I played a game.'],['🌳','Went outside','I went outside.']];
 function style(){if(document.getElementById('t523css'))return;const s=document.createElement('style');s.id='t523css';s.textContent='.t523{position:fixed;inset:0;z-index:999999;background:#071426e8;display:grid;place-items:center;font-family:Arial}.t523box{width:min(980px,96vw);max-height:94vh;overflow:auto;background:#fffdf3;border:6px solid #102342;border-radius:22px;padding:22px;text-align:center}.t523grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.t523card{padding:12px;border:4px solid #174ea6;border-radius:16px;background:white;font-weight:900;font-size:18px}.t523card b{display:block;font-size:48px}.t523go{padding:14px 28px;border:3px solid #102342;border-radius:12px;background:#ffc63d;font-size:22px;font-weight:900}@media(max-width:700px){.t523grid{grid-template-columns:repeat(2,1fr)}}';document.head.appendChild(s)}
 function chart(title,items,cb){style();document.querySelector('.t523')?.remove();const o=document.createElement('div');o.className='t523';o.innerHTML=`<section class="t523box"><h1>${title}</h1><p>Choose one and say the full sentence.</p><div class="t523grid"></div></section>`;items.forEach(x=>{const b=document.createElement('button');b.className='t523card';b.innerHTML=`<b>${x[0]}</b>${x[1]}<small style="display:block">${x[2]}</small>`;b.onclick=()=>{o.remove();cb(x)};o.querySelector('.t523grid').appendChild(b)});document.body.appendChild(o)}
 LessonEngine.prototype.showMissionOpening=function(){if(this.levelId!=='2-A')return oldOpen.call(this);style();this.setSection('opening');document.querySelector('.t523')?.remove();const o=document.createElement('div');o.className='t523';o.innerHTML=`<section class="t523box"><h1>The Alphabet Gate Adventure</h1><h2>Return to Your Academy</h2><p>Captain Fritz and every Academy friend need your help. Find the letters, answer six good questions, and add new pieces to your saved Academy.</p><button class="t523go">Enter the Game</button></section>`;o.querySelector('button').onclick=()=>{o.remove();this.showGreeting(0)};document.body.appendChild(o)};
 LessonEngine.prototype.showGreeting=function(i){if(this.levelId!=='2-A')return oldGreeting.call(this,i);this.setSection('greeting');if(i===0)return chart(`Captain Fritz: How are you today, ${this.studentName}?`,feelings,x=>{this.progress().feeling=x[1].toLowerCase();saveGame(this.scene.save);this.showGreeting(1)});if(i===1)return chart('Captain Fritz: What did you do between classes?',acts,x=>{this.progress().betweenClassActivity=x[1];saveGame(this.scene.save);this.startStory()});this.startStory()};
}

if(typeof BuilderEngine!=='undefined'){
 const oldShow=BuilderEngine.prototype.showBuilder;
 BuilderEngine.prototype.showBuilder=function(){
  if(this.lesson?.id!=='2-A'&&this.lessonEngine?.levelId!=='2-A')return oldShow.call(this);
  const save=this.scene.save;save.builderWorlds=save.builderWorlds||{};const world=save.builderWorlds['academy-world']=save.builderWorlds['academy-world']||{};
  const pieces=new Map();(window.LEVELS||[]).forEach(l=>{if(!l||!['1-A','1-B','1-C','1-D','2-A'].includes(l.id))return;[l.feelingsActivity,l.story,l.phonics,l.reader1,l.reader2].forEach(s=>{const p=s&&s.rewardPiece;if(p&&p.id)pieces.set(p.id,p)})});
  const earned=new Set();Object.values(save.lessonProgress||{}).forEach(p=>(p?.earnedPieces||[]).forEach(id=>{if(pieces.has(id))earned.add(id)}));this.build.requiredPieces.forEach(id=>earned.add(id));
  if(document.getElementById('academy523'))document.getElementById('academy523').remove();const css=document.createElement('style');css.id='academy523';css.textContent='.a523{position:fixed;inset:0;z-index:999999;background:#071426ed;padding:8px;font-family:Arial}.a523s{height:calc(100vh - 16px);background:white;border:5px solid #f6c744;border-radius:20px;display:grid;grid-template-rows:auto 1fr auto;overflow:hidden}.a523h{padding:10px 16px;background:#fff4b8;display:flex;justify-content:space-between}.a523m{display:grid;grid-template-columns:220px 1fr;min-height:0}.a523t{overflow:auto;padding:10px;background:#eef5ff}.a523p{width:100%;padding:8px;margin-bottom:7px;border:2px solid #174ea6;border-radius:9px;background:white;font-weight:800}.a523w{position:relative;overflow:hidden;background:linear-gradient(#9edcff 0 42%,#8dcc72 42%);touch-action:none}.a523o{position:absolute;transform:translate(-50%,-50%);padding:7px;min-width:80px;background:#fff;border:3px solid #174ea6;border-radius:12px;text-align:center;touch-action:none}.a523o b{font-size:38px;display:block}.a523f{padding:9px;text-align:center}.a523f button{padding:10px 18px;margin:0 5px;font-weight:900;border:3px solid #102342;border-radius:10px}.a523f .done{background:#ffc63d}@media(max-width:700px){.a523m{grid-template-columns:1fr;grid-template-rows:130px 1fr}.a523t{display:flex;gap:7px}.a523p{min-width:160px}}';document.head.appendChild(css);
  const o=document.createElement('div');o.className='a523';o.innerHTML='<section class="a523s"><header class="a523h"><b>Your Academy</b><span>Drag pieces anywhere. Every position saves.</span></header><main class="a523m"><aside class="a523t"></aside><div class="a523w"></div></main><footer class="a523f"><button class="later">Save and Keep Building Later</button><button class="done">Finish Tonight’s Build</button></footer></section>';const tray=o.querySelector('.a523t'),stage=o.querySelector('.a523w');let selected='';
  const render=()=>{tray.innerHTML='';stage.innerHTML='';[...earned].forEach(id=>{const p=pieces.get(id)||{id,name:id,icon:'⭐'};const b=document.createElement('button');b.className='a523p';b.textContent=`${p.icon||'⭐'} ${p.name||id}`;b.onclick=()=>{selected=id;if(!world[id])world[id]={x:50,y:55};saveGame(save);render()};tray.appendChild(b);if(world[id]){const d=document.createElement('div');d.className='a523o';d.style.left=world[id].x+'%';d.style.top=world[id].y+'%';d.innerHTML=`<b>${p.icon||'⭐'}</b>${p.name||id}`;let drag=false;d.onpointerdown=e=>{drag=true;d.setPointerCapture?.(e.pointerId)};d.onpointermove=e=>{if(!drag)return;const r=stage.getBoundingClientRect();world[id]={x:Math.max(5,Math.min(95,(e.clientX-r.left)/r.width*100)),y:Math.max(8,Math.min(92,(e.clientY-r.top)/r.height*100))};d.style.left=world[id].x+'%';d.style.top=world[id].y+'%'};d.onpointerup=()=>{drag=false;saveGame(save)};stage.appendChild(d)}})};stage.onclick=e=>{if(!selected||e.target!==stage)return;const r=stage.getBoundingClientRect();world[selected]={x:(e.clientX-r.left)/r.width*100,y:(e.clientY-r.top)/r.height*100};saveGame(save);render()};render();o.querySelector('.later').onclick=()=>o.remove();o.querySelector('.done').onclick=()=>{if(!this.build.requiredPieces.every(id=>world[id]))return alert('Place the three pieces earned tonight before finishing.');saveGame(save);o.remove();this.completeBuild()};document.body.appendChild(o)
 };
}
window.FRITZ_TONIGHT_LESSON={id:'2-A',cast,letters:'A-H',questionWords:['who','what','where','when','why','how'],sharedAcademy:true};
})();