/* Fritz Academy Week 3 curriculum v48.0 */
(function(){
  "use strict";
  const lessons=[
    {
      id:"3-A",chapter:"Week 3",title:"Our Classroom Things",unlocked:false,reward:"Learning Room — Section 1",buildArea:"learning-room",buildStage:1,
      objectives:{speaking:["Name common classroom objects.","Use: This is a ___.","Ask and answer: What is this?"],listening:["Identify classroom objects from spoken clues.","Follow two-step classroom directions.","Recognize beginning sounds /o/ and /p/."],reading:["Read object words in complete sentences.","Use story details to solve a classroom problem.","Read two connected readers with increasing complexity."],writing:["Identify and form O, o, P, and p.","Complete: This is a ___."],phonics:["Recognize O and P.","Produce short-o /o/ and /p/.","Connect sounds to octopus, ox, pencil, and paper."]},
      vocabulary:[{word:"book",display:"This is a book.",picture:"📘"},{word:"pencil",display:"This is a pencil.",picture:"✏️"},{word:"paper",display:"This is paper.",picture:"📄"},{word:"chair",display:"This is a chair.",picture:"🪑"},{word:"table",display:"This is a table.",picture:"🪵"},{word:"bag",display:"This is a bag.",picture:"🎒"}],
      intro:[{speaker:"Captain Fritz",text:"Welcome to Week 3, {studentName}! Today we will prepare our Learning Room."},{speaker:"Captain Fritz",text:"What is this?",responseType:"object-choice"},{speaker:"Captain Fritz",text:"Listen carefully and put each classroom object in the correct place."}],
      feelingChoices:[{id:"ready",label:"I am ready.",emoji:"👍"},{id:"curious",label:"I am curious.",emoji:"🤔"},{id:"helpful",label:"I am helpful.",emoji:"🤝"}],
      feelingsActivity:{title:"Name the Classroom Object",instructions:"Choose the complete sentence that names each object.",questions:[{emoji:"📘",prompt:"What is this?",answer:"This is a book.",options:["This is a book.","This is a chair.","This is a bag."]},{emoji:"✏️",prompt:"What is this?",answer:"This is a pencil.",options:["This is paper.","This is a pencil.","This is a table."]},{emoji:"🎒",prompt:"What is this?",answer:"This is a bag.",options:["This is a chair.","This is a book.","This is a bag."]}],rewardPiece:{id:"classroom-label-board",name:"Classroom Label Board",icon:"🏷️",area:"learning-room",lesson:"3-A"}},
      story:{title:"The Mixed-Up Learning Room",pages:[{text:"Captain Fritz opens the Learning Room, but the classroom things are mixed together."},{text:"Tony finds a pencil under a chair and puts it on the table."},{text:"Nola places the books on the reading shelf."},{text:"Bear carries the paper to the art table while Bash moves the heavy supply box."},{text:"The student checks each label: book, pencil, paper, chair, table, and bag."},{text:"Every object now has a clear place, so the Learning Room is ready."}],questions:[{prompt:"Where does Tony put the pencil?",options:["On the table","Under the shelf","In the garden"],answer:"On the table"},{prompt:"Who puts the books on the shelf?",options:["Nola","Bear","Rascal"],answer:"Nola"},{prompt:"Why is the room ready at the end?",options:["Every object has a clear place","The objects are hidden","The class leaves"],answer:"Every object has a clear place"}],rewardPiece:{id:"organized-supply-shelf",name:"Organized Supply Shelf",icon:"📚",area:"learning-room",lesson:"3-A"}},
      alphabetSong:{title:"Fritz Academy Alphabet Song",rewardMessage:"Sing O and P clearly!",assetPath:"assets/video/alphabet-song.mp4",videoPath:"assets/video/alphabet-song.mp4"},
      phonics:{letterUpper:"O & P",letterLower:"o & p",soundLabel:"short o and /p/",teacherCue:"Say: o, o, ox. Then say: p, p, pencil.",examples:[{word:"ox",icon:"🐂"},{word:"octopus",icon:"🐙"},{word:"pencil",icon:"✏️"},{word:"paper",icon:"📄"}],recognitionQuestion:{prompt:"Choose the uppercase letters for this lesson.",options:["O and P","M and N","Q and R"],answer:"O and P"},lowercaseQuestion:{prompt:"Choose the matching lowercase letters.",options:["o and p","m and n","q and r"],answer:"o and p"},wordQuestion:{prompt:"Which pair begins with O and P sounds?",options:["ox and pencil","moon and nest","queen and rabbit"],answer:"ox and pencil"},rewardPiece:{id:"op-letter-board",name:"O and P Letter Board",icon:"🔤",area:"learning-room",lesson:"3-A"}},
      reader1:{title:"Reader 1: A Pencil and Paper",level:"Easy",pages:["Tony has a pencil.","He has one piece of paper.","The pencil is on the table.","The paper is beside the pencil.","Tony is ready to write."],check:{prompt:"Where is the pencil?",options:["On the table","Under the chair","In the bag"],answer:"On the table"},rewardPiece:{id:"writing-table",name:"Writing Table",icon:"✏️",area:"learning-room",lesson:"3-A"}},
      reader2:{title:"Reader 2: The Right Place",level:"Stretch",pages:["Rascal puts a book inside the supply bag.","Tony explains that books belong on the reading shelf.","Nola shows Rascal the picture label beside the shelf.","Rascal moves the book and checks the other classroom objects.","He puts pencils in the pencil cup and paper on the art table.","Using labels helps everyone keep the Learning Room organized."],check:{prompt:"What helps Rascal organize the room?",options:["The picture labels","A guessing game","The garden map"],answer:"The picture labels"},rewardPiece:{id:"picture-label-set",name:"Picture Label Set",icon:"🖼️",area:"learning-room",lesson:"3-A"}},
      build:{areaId:"learning-room",stage:1,title:"Build the First Learning Room",requiredPieces:["classroom-label-board","organized-supply-shelf","op-letter-board","writing-table","picture-label-set"],completionMessage:"You organized the first section of the Learning Room and named each classroom object."},closingSong:{title:"Fritz Academy Welcome Song",assetPath:"assets/video/welcome-song.mp4",videoPath:"assets/video/welcome-song.mp4",rewardMessage:"Celebrate your organized Learning Room!"},completion:{xp:40,stars:1,unlocks:"3-B",message:"Level 3-A complete! Level 3-B is now unlocked."}
    },
    {
      id:"3-B",chapter:"Week 3",title:"Listen and Do",unlocked:false,reward:"Learning Room — Section 2",buildArea:"learning-room",buildStage:2,
      objectives:{speaking:["Use polite classroom requests.","Say: Please open, close, give, and show.","Answer with: Yes, I can."],listening:["Follow one- and two-step action directions.","Distinguish open, close, give, and show.","Recognize beginning sounds /kw/ and /r/."],reading:["Read short imperative sentences.","Sequence actions from a story.","Use context to identify the correct action."],writing:["Identify and form Q, q, R, and r.","Complete a polite request with please."],phonics:["Recognize Q and R.","Produce /kw/ and /r/.","Connect sounds to queen, quilt, rabbit, and red."]},
      vocabulary:[{word:"open",display:"Please open the book.",picture:"📖"},{word:"close",display:"Please close the bag.",picture:"🎒"},{word:"give",display:"Please give me the pencil.",picture:"🤲"},{word:"show",display:"Please show me the page.",picture:"👀"},{word:"please",display:"Please help me.",picture:"🙏"},{word:"thank you",display:"Thank you.",picture:"😊"}],
      intro:[{speaker:"Captain Fritz",text:"Today we will listen, act, and use polite classroom words."},{speaker:"Captain Fritz",text:"Please open the book, then show me the page.",responseType:"action-sequence"},{speaker:"Captain Fritz",text:"Good listeners wait for the whole direction before they begin."}],
      feelingChoices:[{id:"ready",label:"I am ready.",emoji:"👍"},{id:"focused",label:"I am focused.",emoji:"🧐"},{id:"patient",label:"I am patient.",emoji:"😌"}],
      feelingsActivity:{title:"Listen and Choose",instructions:"Choose the action that follows each polite direction.",questions:[{emoji:"📖",prompt:"Please open the book.",answer:"Open the book.",options:["Open the book.","Close the bag.","Give the pencil."]},{emoji:"🎒",prompt:"Please close the bag.",answer:"Close the bag.",options:["Show the page.","Close the bag.","Open the book."]},{emoji:"✏️",prompt:"Please give me the pencil.",answer:"Give the pencil.",options:["Give the pencil.","Close the book.","Show the chair."]}],rewardPiece:{id:"listening-signal",name:"Listening Signal",icon:"👂",area:"learning-room",lesson:"3-B"}},
      story:{title:"Rascal Learns to Listen First",pages:[{text:"Captain Fritz gives the class two directions: open the blue book and show page four."},{text:"Rascal opens the book quickly before Captain Fritz finishes speaking."},{text:"He turns to page two, then looks confused."},{text:"Tony says, “Wait for the whole direction, then do the first step.”"},{text:"Rascal listens again, opens the blue book, and shows page four."},{text:"Captain Fritz thanks him for listening carefully and trying again."}],questions:[{prompt:"What two actions must the class do?",options:["Open the blue book and show page four","Close the bag and stand up","Find a red pencil and draw"],answer:"Open the blue book and show page four"},{prompt:"Why does Rascal choose the wrong page first?",options:["He begins before the direction is finished","He cannot see the book","Tony hides the page"],answer:"He begins before the direction is finished"},{prompt:"What helps Rascal succeed?",options:["Listening to the whole direction","Guessing again","Leaving the room"],answer:"Listening to the whole direction"}],rewardPiece:{id:"direction-display",name:"Direction Display",icon:"📋",area:"learning-room",lesson:"3-B"}},
      alphabetSong:{title:"Fritz Academy Alphabet Song",rewardMessage:"Sing Q and R clearly!",assetPath:"assets/video/alphabet-song.mp4",videoPath:"assets/video/alphabet-song.mp4"},
      phonics:{letterUpper:"Q & R",letterLower:"q & r",soundLabel:"/kw/ and /r/",teacherCue:"Say: qu, qu, queen. Then say: r, r, rabbit.",examples:[{word:"queen",icon:"👸"},{word:"quilt",icon:"🧵"},{word:"rabbit",icon:"🐇"},{word:"red",icon:"🔴"}],recognitionQuestion:{prompt:"Choose the uppercase letters for this lesson.",options:["Q and R","O and P","S and T"],answer:"Q and R"},lowercaseQuestion:{prompt:"Choose the matching lowercase letters.",options:["q and r","o and p","s and t"],answer:"q and r"},wordQuestion:{prompt:"Which pair begins with Q and R sounds?",options:["queen and rabbit","ox and pencil","sun and turtle"],answer:"queen and rabbit"},rewardPiece:{id:"qr-letter-cards",name:"Q and R Letter Cards",icon:"🔤",area:"learning-room",lesson:"3-B"}},
      reader1:{title:"Reader 1: Open the Red Box",level:"Easy",pages:["Nola has a red box.","Captain Fritz says, “Please open the box.”","Nola opens it.","A quilt card is inside.","Nola shows the card and says, “Thank you.”"],check:{prompt:"What is inside the red box?",options:["A quilt card","A blue pencil","A yellow flower"],answer:"A quilt card"},rewardPiece:{id:"polite-words-box",name:"Polite Words Box",icon:"🎁",area:"learning-room",lesson:"3-B"}},
      reader2:{title:"Reader 2: Two Directions at a Time",level:"Stretch",pages:["Captain Fritz asks the student to take a pencil and close the supply box.","The student waits until both directions are complete.","First, the student takes the pencil.","Next, the student closes the supply box.","Bear checks the two actions and says they are in the correct order.","Listening to all the words makes two-step directions easier to follow."],check:{prompt:"What does the student do first?",options:["Take the pencil","Close the supply box","Open the book"],answer:"Take the pencil"},rewardPiece:{id:"two-step-path",name:"Two-Step Learning Path",icon:"1️⃣2️⃣",area:"learning-room",lesson:"3-B"}},
      build:{areaId:"learning-room",stage:2,title:"Add the Listening Center",requiredPieces:["listening-signal","direction-display","qr-letter-cards","polite-words-box","two-step-path"],completionMessage:"You built a Listening Center and practiced polite two-step directions."},closingSong:{title:"Fritz Academy Welcome Song",assetPath:"assets/video/welcome-song.mp4",videoPath:"assets/video/welcome-song.mp4",rewardMessage:"Celebrate careful listening and polite words!"},completion:{xp:40,stars:1,unlocks:"3-C",message:"Level 3-B complete! Level 3-C is now unlocked."}
    }
  ];
  if(!Array.isArray(window.LEVELS)) return;
  lessons.forEach(lesson=>{const index=window.LEVELS.findIndex(item=>item&&item.id===lesson.id);if(index>=0)window.LEVELS[index]=lesson;else window.LEVELS.push(lesson);});
})();
